/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AssignTaskRequest,
  CreateSampleReceiptRequest,
  ErrorResponse,
  FlowHistoryEntry,
  ReceiptsListReceipts200,
  ReceiptsListReceiptsParams,
  SampleReceipt,
  UpdateSampleReceiptRequest
} from '.././model';





export const receiptsListReceipts = (
    params?: ReceiptsListReceiptsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReceiptsListReceipts200>> => {
    
    
    return axios.default.get(
      `/api/receipts`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getReceiptsListReceiptsQueryKey = (params?: ReceiptsListReceiptsParams,) => {
    return [
    `/api/receipts`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getReceiptsListReceiptsQueryOptions = <TData = Awaited<ReturnType<typeof receiptsListReceipts>>, TError = AxiosError<ErrorResponse>>(params?: ReceiptsListReceiptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof receiptsListReceipts>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReceiptsListReceiptsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof receiptsListReceipts>>> = ({ signal }) => receiptsListReceipts(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof receiptsListReceipts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReceiptsListReceiptsQueryResult = NonNullable<Awaited<ReturnType<typeof receiptsListReceipts>>>
export type ReceiptsListReceiptsQueryError = AxiosError<ErrorResponse>


export function useReceiptsListReceipts<TData = Awaited<ReturnType<typeof receiptsListReceipts>>, TError = AxiosError<ErrorResponse>>(
 params: undefined |  ReceiptsListReceiptsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof receiptsListReceipts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof receiptsListReceipts>>,
          TError,
          Awaited<ReturnType<typeof receiptsListReceipts>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReceiptsListReceipts<TData = Awaited<ReturnType<typeof receiptsListReceipts>>, TError = AxiosError<ErrorResponse>>(
 params?: ReceiptsListReceiptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof receiptsListReceipts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof receiptsListReceipts>>,
          TError,
          Awaited<ReturnType<typeof receiptsListReceipts>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReceiptsListReceipts<TData = Awaited<ReturnType<typeof receiptsListReceipts>>, TError = AxiosError<ErrorResponse>>(
 params?: ReceiptsListReceiptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof receiptsListReceipts>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useReceiptsListReceipts<TData = Awaited<ReturnType<typeof receiptsListReceipts>>, TError = AxiosError<ErrorResponse>>(
 params?: ReceiptsListReceiptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof receiptsListReceipts>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReceiptsListReceiptsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const receiptsCreateReceipt = (
    createSampleReceiptRequest: CreateSampleReceiptRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SampleReceipt>> => {
    
    
    return axios.default.post(
      `/api/receipts`,
      createSampleReceiptRequest,options
    );
  }



export const getReceiptsCreateReceiptMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof receiptsCreateReceipt>>, TError,{data: CreateSampleReceiptRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof receiptsCreateReceipt>>, TError,{data: CreateSampleReceiptRequest}, TContext> => {

const mutationKey = ['receiptsCreateReceipt'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof receiptsCreateReceipt>>, {data: CreateSampleReceiptRequest}> = (props) => {
          const {data} = props ?? {};

          return  receiptsCreateReceipt(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReceiptsCreateReceiptMutationResult = NonNullable<Awaited<ReturnType<typeof receiptsCreateReceipt>>>
    export type ReceiptsCreateReceiptMutationBody = CreateSampleReceiptRequest
    export type ReceiptsCreateReceiptMutationError = AxiosError<ErrorResponse>

    export const useReceiptsCreateReceipt = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof receiptsCreateReceipt>>, TError,{data: CreateSampleReceiptRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof receiptsCreateReceipt>>,
        TError,
        {data: CreateSampleReceiptRequest},
        TContext
      > => {

      const mutationOptions = getReceiptsCreateReceiptMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const receiptsGetReceipt = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SampleReceipt>> => {
    
    
    return axios.default.get(
      `/api/receipts/${id}`,options
    );
  }




export const getReceiptsGetReceiptQueryKey = (id?: string,) => {
    return [
    `/api/receipts/${id}`
    ] as const;
    }

    
export const getReceiptsGetReceiptQueryOptions = <TData = Awaited<ReturnType<typeof receiptsGetReceipt>>, TError = AxiosError<ErrorResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof receiptsGetReceipt>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReceiptsGetReceiptQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof receiptsGetReceipt>>> = ({ signal }) => receiptsGetReceipt(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof receiptsGetReceipt>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReceiptsGetReceiptQueryResult = NonNullable<Awaited<ReturnType<typeof receiptsGetReceipt>>>
export type ReceiptsGetReceiptQueryError = AxiosError<ErrorResponse>


export function useReceiptsGetReceipt<TData = Awaited<ReturnType<typeof receiptsGetReceipt>>, TError = AxiosError<ErrorResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof receiptsGetReceipt>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof receiptsGetReceipt>>,
          TError,
          Awaited<ReturnType<typeof receiptsGetReceipt>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReceiptsGetReceipt<TData = Awaited<ReturnType<typeof receiptsGetReceipt>>, TError = AxiosError<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof receiptsGetReceipt>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof receiptsGetReceipt>>,
          TError,
          Awaited<ReturnType<typeof receiptsGetReceipt>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReceiptsGetReceipt<TData = Awaited<ReturnType<typeof receiptsGetReceipt>>, TError = AxiosError<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof receiptsGetReceipt>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useReceiptsGetReceipt<TData = Awaited<ReturnType<typeof receiptsGetReceipt>>, TError = AxiosError<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof receiptsGetReceipt>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReceiptsGetReceiptQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const receiptsUpdateReceipt = (
    id: string,
    updateSampleReceiptRequest: UpdateSampleReceiptRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SampleReceipt>> => {
    
    
    return axios.default.put(
      `/api/receipts/${id}`,
      updateSampleReceiptRequest,options
    );
  }



export const getReceiptsUpdateReceiptMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof receiptsUpdateReceipt>>, TError,{id: string;data: UpdateSampleReceiptRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof receiptsUpdateReceipt>>, TError,{id: string;data: UpdateSampleReceiptRequest}, TContext> => {

const mutationKey = ['receiptsUpdateReceipt'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof receiptsUpdateReceipt>>, {id: string;data: UpdateSampleReceiptRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  receiptsUpdateReceipt(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReceiptsUpdateReceiptMutationResult = NonNullable<Awaited<ReturnType<typeof receiptsUpdateReceipt>>>
    export type ReceiptsUpdateReceiptMutationBody = UpdateSampleReceiptRequest
    export type ReceiptsUpdateReceiptMutationError = AxiosError<ErrorResponse>

    export const useReceiptsUpdateReceipt = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof receiptsUpdateReceipt>>, TError,{id: string;data: UpdateSampleReceiptRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof receiptsUpdateReceipt>>,
        TError,
        {id: string;data: UpdateSampleReceiptRequest},
        TContext
      > => {

      const mutationOptions = getReceiptsUpdateReceiptMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const receiptsDeleteReceipt = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/receipts/${id}`,options
    );
  }



export const getReceiptsDeleteReceiptMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof receiptsDeleteReceipt>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof receiptsDeleteReceipt>>, TError,{id: string}, TContext> => {

const mutationKey = ['receiptsDeleteReceipt'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof receiptsDeleteReceipt>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  receiptsDeleteReceipt(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReceiptsDeleteReceiptMutationResult = NonNullable<Awaited<ReturnType<typeof receiptsDeleteReceipt>>>
    
    export type ReceiptsDeleteReceiptMutationError = AxiosError<ErrorResponse>

    export const useReceiptsDeleteReceipt = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof receiptsDeleteReceipt>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof receiptsDeleteReceipt>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getReceiptsDeleteReceiptMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const receiptsGetReceiptHistory = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FlowHistoryEntry[]>> => {
    
    
    return axios.default.get(
      `/api/receipts/${id}/history`,options
    );
  }




export const getReceiptsGetReceiptHistoryQueryKey = (id?: string,) => {
    return [
    `/api/receipts/${id}/history`
    ] as const;
    }

    
export const getReceiptsGetReceiptHistoryQueryOptions = <TData = Awaited<ReturnType<typeof receiptsGetReceiptHistory>>, TError = AxiosError<ErrorResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof receiptsGetReceiptHistory>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReceiptsGetReceiptHistoryQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof receiptsGetReceiptHistory>>> = ({ signal }) => receiptsGetReceiptHistory(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof receiptsGetReceiptHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReceiptsGetReceiptHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof receiptsGetReceiptHistory>>>
export type ReceiptsGetReceiptHistoryQueryError = AxiosError<ErrorResponse>


export function useReceiptsGetReceiptHistory<TData = Awaited<ReturnType<typeof receiptsGetReceiptHistory>>, TError = AxiosError<ErrorResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof receiptsGetReceiptHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof receiptsGetReceiptHistory>>,
          TError,
          Awaited<ReturnType<typeof receiptsGetReceiptHistory>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReceiptsGetReceiptHistory<TData = Awaited<ReturnType<typeof receiptsGetReceiptHistory>>, TError = AxiosError<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof receiptsGetReceiptHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof receiptsGetReceiptHistory>>,
          TError,
          Awaited<ReturnType<typeof receiptsGetReceiptHistory>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReceiptsGetReceiptHistory<TData = Awaited<ReturnType<typeof receiptsGetReceiptHistory>>, TError = AxiosError<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof receiptsGetReceiptHistory>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useReceiptsGetReceiptHistory<TData = Awaited<ReturnType<typeof receiptsGetReceiptHistory>>, TError = AxiosError<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof receiptsGetReceiptHistory>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReceiptsGetReceiptHistoryQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const receiptsAssignTask = (
    id: string,
    assignTaskRequest: AssignTaskRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SampleReceipt>> => {
    
    
    return axios.default.put(
      `/api/receipts/${id}/task`,
      assignTaskRequest,options
    );
  }



export const getReceiptsAssignTaskMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof receiptsAssignTask>>, TError,{id: string;data: AssignTaskRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof receiptsAssignTask>>, TError,{id: string;data: AssignTaskRequest}, TContext> => {

const mutationKey = ['receiptsAssignTask'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof receiptsAssignTask>>, {id: string;data: AssignTaskRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  receiptsAssignTask(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReceiptsAssignTaskMutationResult = NonNullable<Awaited<ReturnType<typeof receiptsAssignTask>>>
    export type ReceiptsAssignTaskMutationBody = AssignTaskRequest
    export type ReceiptsAssignTaskMutationError = AxiosError<ErrorResponse>

    export const useReceiptsAssignTask = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof receiptsAssignTask>>, TError,{id: string;data: AssignTaskRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof receiptsAssignTask>>,
        TError,
        {id: string;data: AssignTaskRequest},
        TContext
      > => {

      const mutationOptions = getReceiptsAssignTaskMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    