// 静态本地菜单树 — Sprint 2 Batch 0。
//
// nextjs 仓菜单来自 saas（/api/saas/me/menus 按 appCode 过滤），react 仓是
// 前端 only 镜像仓、无 /api route，菜单树落本地静态常量（MenuNode 形状与
// nextjs sidebar-nav 手写接口一致）。code 沿用 saas 菜单码（m-*），供
// data-fn 锚点（M98.F04.<code>）与未来跨仓对齐。
import type { MenuNode } from "./sidebar-nav";

export const APP_CODE = "lab-management";

export const APP_NAME = "实验室管理系统";

/** 6 组 26 项：总览 / 基础数据 / 试验过程 / 检测能力 / 报告 / 统计 */
export const MENU_TREE: MenuNode[] = [
  {
    id: "g-overview",
    appId: APP_CODE,
    code: "m-overview",
    name: "总览",
    icon: "LayoutDashboard",
    type: "group",
    sortOrder: 1,
    children: [
      {
        id: "p-dashboard",
        appId: APP_CODE,
        code: "m-dashboard",
        name: "仪表盘",
        path: "",
        icon: "LayoutDashboard",
        type: "page",
        sortOrder: 1,
        children: [],
      },
    ],
  },
  {
    id: "g-basedata",
    appId: APP_CODE,
    code: "m-basedata",
    name: "基础数据",
    icon: "Database",
    type: "group",
    sortOrder: 2,
    children: [
      {
        id: "p-models",
        appId: APP_CODE,
        code: "m-models",
        name: "型号维护",
        path: "models",
        icon: "Database",
        type: "page",
        sortOrder: 1,
        children: [],
      },
      {
        id: "p-specifications",
        appId: APP_CODE,
        code: "m-specifications",
        name: "规格维护",
        path: "specifications",
        icon: "Database",
        type: "page",
        sortOrder: 2,
        children: [],
      },
      {
        id: "p-grades",
        appId: APP_CODE,
        code: "m-grades",
        name: "等级维护",
        path: "grades",
        icon: "Database",
        type: "page",
        sortOrder: 3,
        children: [],
      },
      {
        id: "p-brands",
        appId: APP_CODE,
        code: "m-brands",
        name: "牌号维护",
        path: "brands",
        icon: "Database",
        type: "page",
        sortOrder: 4,
        children: [],
      },
      {
        id: "p-contracts",
        appId: APP_CODE,
        code: "m-contracts",
        name: "合同管理",
        path: "contracts",
        icon: "ClipboardList",
        type: "page",
        sortOrder: 5,
        children: [],
      },
      {
        id: "p-report-names",
        appId: APP_CODE,
        code: "m-report-names",
        name: "报告名称维护",
        path: "report-names",
        icon: "ScrollText",
        type: "page",
        sortOrder: 6,
        children: [],
      },
      {
        id: "p-param-interfaces",
        appId: APP_CODE,
        code: "m-param-interfaces",
        name: "参数界面维护",
        path: "param-interfaces",
        icon: "Wrench",
        type: "page",
        sortOrder: 7,
        children: [],
      },
    ],
  },
  {
    id: "g-process",
    appId: APP_CODE,
    code: "m-process",
    name: "试验过程",
    icon: "FlaskConical",
    type: "group",
    sortOrder: 3,
    children: [
      {
        id: "p-receipts",
        appId: APP_CODE,
        code: "m-receipts",
        name: "接样管理",
        path: "receipts",
        icon: "FlaskConical",
        type: "page",
        sortOrder: 1,
        children: [],
      },
      {
        id: "p-task-assignment",
        appId: APP_CODE,
        code: "m-task-assignment",
        name: "任务分配",
        path: "task-assignment",
        icon: "ClipboardList",
        type: "page",
        sortOrder: 2,
        children: [],
      },
      {
        id: "p-data-entry",
        appId: APP_CODE,
        code: "m-data-entry",
        name: "数据录入",
        path: "data-entry",
        icon: "TestTube2",
        type: "page",
        sortOrder: 3,
        children: [],
      },
    ],
  },
  {
    id: "g-capability",
    appId: APP_CODE,
    code: "m-capability",
    name: "检测能力",
    icon: "Beaker",
    type: "group",
    sortOrder: 4,
    children: [
      {
        id: "p-inspection-objects",
        appId: APP_CODE,
        code: "m-inspection-objects",
        name: "检测专项",
        path: "inspection-objects",
        icon: "Beaker",
        type: "page",
        sortOrder: 1,
        children: [],
      },
      {
        id: "p-inspection-standards",
        appId: APP_CODE,
        code: "m-inspection-standards",
        name: "检测标准",
        path: "inspection-standards",
        icon: "ScrollText",
        type: "page",
        sortOrder: 2,
        children: [],
      },
      {
        id: "p-inspection-parameters",
        appId: APP_CODE,
        code: "m-inspection-parameters",
        name: "检测参数",
        path: "inspection-parameters",
        icon: "Activity",
        type: "page",
        sortOrder: 3,
        children: [],
      },
      {
        id: "p-inspection-specialties",
        appId: APP_CODE,
        code: "m-inspection-specialties",
        name: "检测项目",
        path: "inspection-specialties",
        icon: "PackageSearch",
        type: "page",
        sortOrder: 4,
        children: [],
      },
      {
        id: "p-inspection-technical-requirements",
        appId: APP_CODE,
        code: "m-inspection-technical-requirements",
        name: "技术要求",
        path: "inspection-technical-requirements",
        icon: "Shield",
        type: "page",
        sortOrder: 5,
        children: [],
      },
      {
        id: "p-inspection-calculation-rules",
        appId: APP_CODE,
        code: "m-inspection-calculation-rules",
        name: "计算规则",
        path: "inspection-calculation-rules",
        icon: "Settings",
        type: "page",
        sortOrder: 6,
        children: [],
      },
    ],
  },
  {
    id: "g-reports",
    appId: APP_CODE,
    code: "m-reports",
    name: "报告",
    icon: "FileText",
    type: "group",
    sortOrder: 5,
    children: [
      {
        id: "p-report-issue",
        appId: APP_CODE,
        code: "m-report-issue",
        name: "报告发放",
        path: "report-issue",
        icon: "FileText",
        type: "page",
        sortOrder: 1,
        children: [],
      },
      {
        id: "p-report-review",
        appId: APP_CODE,
        code: "m-report-review",
        name: "报告审核",
        path: "report-review",
        icon: "FileText",
        type: "page",
        sortOrder: 2,
        children: [],
      },
      {
        id: "p-report-approve",
        appId: APP_CODE,
        code: "m-report-approve",
        name: "报告批准",
        path: "report-approve",
        icon: "FileText",
        type: "page",
        sortOrder: 3,
        children: [],
      },
      {
        id: "p-report-archive",
        appId: APP_CODE,
        code: "m-report-archive",
        name: "报告归档",
        path: "report-archive",
        icon: "ScrollText",
        type: "page",
        sortOrder: 4,
        children: [],
      },
    ],
  },
  {
    id: "g-stats",
    appId: APP_CODE,
    code: "m-stats",
    name: "统计",
    icon: "ListChecks",
    type: "group",
    sortOrder: 6,
    children: [
      {
        id: "p-summary",
        appId: APP_CODE,
        code: "m-summary",
        name: "报告汇总",
        path: "summary",
        icon: "ListChecks",
        type: "page",
        sortOrder: 1,
        children: [],
      },
    ],
  },
];
