/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

/**
 * 已废弃 (ADR-0014)
 */
export type AuthHeaderKind = typeof AuthHeaderKind[keyof typeof AuthHeaderKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthHeaderKind = {
  Authorization: 'Authorization',
  'X-Auth-Token': 'X-Auth-Token',
} as const;
