/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type AuthStateAuthenticatedValueKind =
  (typeof AuthStateAuthenticatedValueKind)[keyof typeof AuthStateAuthenticatedValueKind];

 
export const AuthStateAuthenticatedValueKind = {
  authenticated: "authenticated",
} as const;
