/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { AuthStateIdleKind } from "./authStateIdleKind";
import type { AuthStateIdleValue } from "./authStateIdleValue";

export interface AuthStateIdle {
  kind: AuthStateIdleKind;
  value: AuthStateIdleValue;
}
