/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { OAuthResponseType } from "./oAuthResponseType";

export type AuthSsoAuthorizeParams = {
  response_type: OAuthResponseType;
  client_id: string;
  redirect_uri: string;
  state: string;
};
