/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type AuthStateAwaitingTenantValueKind =
  (typeof AuthStateAwaitingTenantValueKind)[keyof typeof AuthStateAwaitingTenantValueKind];

 
export const AuthStateAwaitingTenantValueKind = {
  awaiting_tenant: "awaiting_tenant",
} as const;
