/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { AuthStateAwaitingTenantValueKind } from "./authStateAwaitingTenantValueKind";
import type { CurrentUser } from "./currentUser";
import type { MyTenant } from "./myTenant";

export type AuthStateAwaitingTenantValue = {
  kind: AuthStateAwaitingTenantValueKind;
  user: CurrentUser;
  tenants: MyTenant[];
};
