/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type AuthStateAnonymousValueKind = typeof AuthStateAnonymousValueKind[keyof typeof AuthStateAnonymousValueKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthStateAnonymousValueKind = {
  anonymous: 'anonymous',
} as const;
