/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type AuthStateAwaitingTenantKind =
  (typeof AuthStateAwaitingTenantKind)[keyof typeof AuthStateAwaitingTenantKind];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthStateAwaitingTenantKind = {
  awaiting_tenant: "awaiting_tenant",
} as const;
