/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { AuthStateAnonymousKind } from './authStateAnonymousKind';
import type { AuthStateAnonymousValue } from './authStateAnonymousValue';

export interface AuthStateAnonymous {
  kind: AuthStateAnonymousKind;
  value: AuthStateAnonymousValue;
}
