/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { AuthStateAwaitingTenantKind } from './authStateAwaitingTenantKind';
import type { AuthStateAwaitingTenantValue } from './authStateAwaitingTenantValue';

export interface AuthStateAwaitingTenant {
  kind: AuthStateAwaitingTenantKind;
  value: AuthStateAwaitingTenantValue;
}
