/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { AuthStateAuthenticatedKind } from "./authStateAuthenticatedKind";
import type { AuthStateAuthenticatedValue } from "./authStateAuthenticatedValue";

export interface AuthStateAuthenticated {
  kind: AuthStateAuthenticatedKind;
  value: AuthStateAuthenticatedValue;
}
