/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type AuthStateAnonymousKind = typeof AuthStateAnonymousKind[keyof typeof AuthStateAnonymousKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthStateAnonymousKind = {
  anonymous: 'anonymous',
} as const;
