/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { AuthStateAuthenticatedValueKind } from "./authStateAuthenticatedValueKind";
import type { CurrentUser } from "./currentUser";
import type { MyTenant } from "./myTenant";

export type AuthStateAuthenticatedValue = {
  kind: AuthStateAuthenticatedValueKind;
  user: CurrentUser;
  tenant: MyTenant;
  permissions: string[];
  /** unix ms */
  tokenExpiresAt: number;
};
