/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type AuthStateAuthenticatedKind =
  (typeof AuthStateAuthenticatedKind)[keyof typeof AuthStateAuthenticatedKind];

 
export const AuthStateAuthenticatedKind = {
  authenticated: "authenticated",
} as const;
