/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { BackendId } from "./backendId";
import type { BackendConfig } from "./backendConfig";

/**
 * 已废弃 (ADR-0014);运行时注册表:当前激活 + 可切列表
 */
export interface BackendRegistry {
  /** 当前激活后端 */
  active: BackendId;
  /** 可切换列表(通常包含全部 4 个槽位) */
  available: BackendConfig[];
}
