/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

/**
 * 已废弃 (ADR-0014);3 个槽位,id 锁定避免拼写漂移。msw 成员 2026-09-17 随 msw 仓剔除删除
 */
export type BackendId = (typeof BackendId)[keyof typeof BackendId];

export const BackendId = {
  nextjs: "nextjs",
  springboot: "springboot",
  aspnetcore: "aspnetcore",
} as const;
