/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { CalculationAlgorithmType } from './calculationAlgorithmType';

export interface CalculationMethod {
  inspectionObjectCode: string;
  inspectionParameterCode: string;
  testingStandardCode?: string;
  reportNameCode?: string;
  algorithmType: CalculationAlgorithmType;
  specimenCount: number;
  formula?: string;
  conditions?: string;
  roundingRule?: string;
  remark?: string;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}
