/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { InspectionSpec } from './inspectionSpec';

export type CatalogListSpecs200 = {
  items: InspectionSpec[];
  page: number;
  pageSize: number;
  total: number;
};
