/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { InspectionGrade } from './inspectionGrade';

export type CatalogListGrades200 = {
  items: InspectionGrade[];
  page: number;
  pageSize: number;
  total: number;
};
