/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { InspectionModel } from './inspectionModel';

export type CatalogListModels200 = {
  items: InspectionModel[];
  page: number;
  pageSize: number;
  total: number;
};
