/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { InspectionBrand } from "./inspectionBrand";

export type CatalogListBrands200 = {
  items: InspectionBrand[];
  page: number;
  pageSize: number;
  total: number;
};
