/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type CatalogListModelsParams = {
page?: number;
pageSize?: number;
inspectionObjectCode?: string;
keyword?: string;
};
