/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type ContractStatus = (typeof ContractStatus)[keyof typeof ContractStatus];

 
export const ContractStatus = {
  active: "active",
  archived: "archived",
} as const;
