/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export interface CreateCatalogEntryRequest {
  code: string;
  inspectionObjectCode?: string;
  name: string;
  remark?: string;
  sortOrder?: number;
}
