/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { InspectionParameterSourceType } from './inspectionParameterSourceType';

export interface CreateInspectionParameterRequest {
  code: string;
  name: string;
  rawName: string;
  canonicalName: string;
  methodText?: string;
  aliases?: string[];
  unit?: string;
  sourceType?: InspectionParameterSourceType;
  sortOrder?: number;
}
