/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { ExtFieldDef } from './extFieldDef';

export interface CreateInspectionReportNameRequest {
  code: string;
  name: string;
  fullName?: string;
  templatePath?: string;
  summaryName?: string;
  extFields?: ExtFieldDef[];
  description?: string;
  sortOrder?: number;
}
