/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export interface CurrentUser {
  id: string;
  username: string;
  displayName?: string;
  roleCode?: string;
}
