/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { DashboardStatsReportCountByStatus } from './dashboardStatsReportCountByStatus';
import type { DashboardStatsQualifiedRateByMaterial } from './dashboardStatsQualifiedRateByMaterial';
import type { DashboardStatsReportOutputByStatus } from './dashboardStatsReportOutputByStatus';
import type { DashboardStatsFunnelByStage } from './dashboardStatsFunnelByStage';

export interface DashboardStats {
  contractCount: number;
  receiptCount: number;
  sampleCount: number;
  reportCountByStatus: DashboardStatsReportCountByStatus;
  pendingTaskCount: number;
  todayTestCount: number;
  qualifiedRateByMaterial: DashboardStatsQualifiedRateByMaterial;
  reportOutputByStatus: DashboardStatsReportOutputByStatus;
  funnelByStage: DashboardStatsFunnelByStage;
}
