/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { MaterialQualifiedRate } from './materialQualifiedRate';

export type DashboardStatsQualifiedRateByMaterial = {
  concrete: MaterialQualifiedRate;
  rebar: MaterialQualifiedRate;
  sand: MaterialQualifiedRate;
};
