/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { ExtFieldDefType } from "./extFieldDefType";
import type { ExtFieldDefSource } from "./extFieldDefSource";

export interface ExtFieldDef {
  key: string;
  label: string;
  type: ExtFieldDefType;
  required?: boolean;
  options?: string[];
  tag?: string;
  source?: ExtFieldDefSource;
}
