/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type ExtFieldDefType = (typeof ExtFieldDefType)[keyof typeof ExtFieldDefType];

export const ExtFieldDefType = {
  text: "text",
  number: "number",
  date: "date",
  select: "select",
} as const;
