/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { FlowAction } from "./flowAction";
import type { FlowStatus } from "./flowStatus";

export interface FlowHistoryEntry {
  action: FlowAction;
  from: FlowStatus;
  to: FlowStatus;
  operator: string;
  at: string;
  reason?: string;
}
