/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { FlowAction } from "./flowAction";

export interface FlowActionRequest {
  ids: string[];
  action: FlowAction;
  operator: string;
  reason?: string;
}
