/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type FlowAction = (typeof FlowAction)[keyof typeof FlowAction];

export const FlowAction = {
  submit: "submit",
  return: "return",
  withdraw: "withdraw",
} as const;
