/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { ObjectParameterLink } from "./objectParameterLink";

export type InspectionDictionaryListObjectParameterLinks200 = {
  items: ObjectParameterLink[];
  page: number;
  pageSize: number;
  total: number;
};
