/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type InspectionStandardRole =
  (typeof InspectionStandardRole)[keyof typeof InspectionStandardRole];

export const InspectionStandardRole = {
  TESTING: "TESTING",
  JUDGMENT: "JUDGMENT",
} as const;
