/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type InspectionStandardStatus = typeof InspectionStandardStatus[keyof typeof InspectionStandardStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InspectionStandardStatus = {
  active: 'active',
  superseded: 'superseded',
  draft: 'draft',
} as const;
