/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { ObjectStandardLink } from './objectStandardLink';

export type InspectionDictionaryListObjectStandardLinks200 = {
  items: ObjectStandardLink[];
  page: number;
  pageSize: number;
  total: number;
};
