/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { InspectionParameter } from './inspectionParameter';

export type InspectionDictionaryListParameters200 = {
  items: InspectionParameter[];
  page: number;
  pageSize: number;
  total: number;
};
