/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type InspectionParameterSourceType =
  (typeof InspectionParameterSourceType)[keyof typeof InspectionParameterSourceType];

 
export const InspectionParameterSourceType = {
  official: "official",
  custom: "custom",
} as const;
