/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { InspectionStandard } from "./inspectionStandard";

export type InspectionDictionaryListStandards200 = {
  items: InspectionStandard[];
  page: number;
  pageSize: number;
  total: number;
};
