/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { InspectionParameterSourceType } from "./inspectionParameterSourceType";

export type InspectionDictionaryListParametersParams = {
  page?: number;
  pageSize?: number;
  keyword?: string;
  sourceType?: InspectionParameterSourceType;
};
