/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type OAuthResponseType =
  (typeof OAuthResponseType)[keyof typeof OAuthResponseType];

export const OAuthResponseType = {
  code: "code",
} as const;
