/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type OAuthGrantType = (typeof OAuthGrantType)[keyof typeof OAuthGrantType];

export const OAuthGrantType = {
  authorization_code: "authorization_code",
} as const;
