/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { QualificationLevel } from "./qualificationLevel";

export interface ObjectParameterLink {
  inspectionObjectCode: string;
  inspectionParameterCode: string;
  qualificationLevel: QualificationLevel;
  sourcePage?: number;
  remark?: string;
}
