/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { ParamInterface } from './paramInterface';

export type ParamInterfacesListParamInterfaces200 = {
  items: ParamInterface[];
  page: number;
  pageSize: number;
  total: number;
};
