/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { ParamInterfaceLink } from './paramInterfaceLink';

export type ParamInterfacesListParamInterfaceLinks200 = {
  items: ParamInterfaceLink[];
  page: number;
  pageSize: number;
  total: number;
};
