/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { ParamInterfaceLinkConfig } from "./paramInterfaceLinkConfig";

export interface ParamInterfaceLink {
  inspectionParameterCode: string;
  paramInterfaceCode: string;
  reportNameCode?: string;
  config?: ParamInterfaceLinkConfig;
}
