/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { ParamInterfaceConfig } from './paramInterfaceConfig';

export interface ParamInterface {
  code: string;
  name?: string;
  componentPath: string;
  description?: string;
  isOfficial?: boolean;
  sortOrder: number;
  config?: ParamInterfaceConfig;
  createdAt: string;
  updatedAt: string;
}
