/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type QualificationLevel =
  (typeof QualificationLevel)[keyof typeof QualificationLevel];

 
export const QualificationLevel = {
  QUALIFIED: "QUALIFIED",
  RESTRICTED: "RESTRICTED",
} as const;
