/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { SampleReceipt } from "./sampleReceipt";

export type ReceiptsListReceipts200 = {
  items: SampleReceipt[];
  page: number;
  pageSize: number;
  total: number;
};
