/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type ReceiptResult = typeof ReceiptResult[keyof typeof ReceiptResult];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReceiptResult = {
  pass: 'pass',
  fail: 'fail',
  '': '',
} as const;
