/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { FlowStatus } from "./flowStatus";

export type ReceiptsListReceiptsParams = {
  page?: number;
  pageSize?: number;
  keyword?: string;
  contractId?: string;
  flowStatus?: FlowStatus;
  filter?: string;
};
