/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { ReportNameStandardLink } from "./reportNameStandardLink";

export type ReportNamesListReportNameStandardLinks200 = {
  items: ReportNameStandardLink[];
  page: number;
  pageSize: number;
  total: number;
};
