/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { InspectionStandardRole } from "./inspectionStandardRole";

export type ReportNamesUnlinkReportNameStandardBody = {
  reportNameCode: string;
  inspectionStandardCode: string;
  role: InspectionStandardRole;
};
