/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export interface ReportNameParameterLink {
  reportNameCode: string;
  inspectionParameterCode: string;
  remark?: string;
}
