/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { ReportNameParameterLink } from './reportNameParameterLink';

export type ReportNamesListReportNameParameterLinks200 = {
  items: ReportNameParameterLink[];
  page: number;
  pageSize: number;
  total: number;
};
