/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { ObjectReportNameLink } from "./objectReportNameLink";

export type ReportNamesListObjectReportNameLinks200 = {
  items: ObjectReportNameLink[];
  page: number;
  pageSize: number;
  total: number;
};
