/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type RequirementVerificationStatus =
  (typeof RequirementVerificationStatus)[keyof typeof RequirementVerificationStatus];

export const RequirementVerificationStatus = {
  draft: "draft",
  reviewed: "reviewed",
  verified: "verified",
  rejected: "rejected",
} as const;
