/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export type RequirementJudgmentMode = typeof RequirementJudgmentMode[keyof typeof RequirementJudgmentMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequirementJudgmentMode = {
  automatic: 'automatic',
  manual: 'manual',
} as const;
