/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { OAuthGrantType } from './oAuthGrantType';

export interface SsoCallbackRequest {
  grant_type: OAuthGrantType;
  code: string;
  redirect_uri: string;
  state: string;
}
