/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { SummaryColumn } from './summaryColumn';
import type { SummaryDataRowsItem } from './summaryDataRowsItem';

export interface SummaryData {
  summaryName: string;
  columns: SummaryColumn[];
  rows: SummaryDataRowsItem[];
}
