/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { RequirementVerificationStatus } from "./requirementVerificationStatus";

export type TechnicalRequirementsListTechnicalRequirementsParams = {
  inspectionObjectCode?: string;
  inspectionParameterCode?: string;
  judgmentStandardCode?: string;
  verificationStatus?: RequirementVerificationStatus;
};
