/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { TestRecord } from './testRecord';

export type TestRecordsListTestRecords200 = {
  items: TestRecord[];
  page: number;
  pageSize: number;
  total: number;
};
