/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { TokenStorageKeysAccessToken } from './tokenStorageKeysAccessToken';
import type { TokenStorageKeysRefreshToken } from './tokenStorageKeysRefreshToken';
import type { TokenStorageKeysActiveTenantId } from './tokenStorageKeysActiveTenantId';
import type { TokenStorageKeysPermissionsCache } from './tokenStorageKeysPermissionsCache';

/**
 * 前端持久化 key 命名约定;后端契约不感知,但前端实现必须遵守
 */
export interface TokenStorageKeys {
  /** Bearer token */
  accessToken: TokenStorageKeysAccessToken;
  /** refresh token(与 accessToken 分存,便于隔离 XSS 影响面) */
  refreshToken: TokenStorageKeysRefreshToken;
  /** 当前选中租户 ID(authenticated 态缓存) */
  activeTenantId: TokenStorageKeysActiveTenantId;
  /** permissions 缓存(避免每次路由跳转都打 /auth/permissions) */
  permissionsCache: TokenStorageKeysPermissionsCache;
}
