/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

/**
 * refresh token(与 accessToken 分存,便于隔离 XSS 影响面)
 */
export type TokenStorageKeysRefreshToken =
  (typeof TokenStorageKeysRefreshToken)[keyof typeof TokenStorageKeysRefreshToken];

 
export const TokenStorageKeysRefreshToken = {
  labrefreshToken: "lab.refreshToken",
} as const;
