/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

/**
 * 当前选中租户 ID(authenticated 态缓存)
 */
export type TokenStorageKeysActiveTenantId =
  (typeof TokenStorageKeysActiveTenantId)[keyof typeof TokenStorageKeysActiveTenantId];

 
export const TokenStorageKeysActiveTenantId = {
  labactiveTenantId: "lab.activeTenantId",
} as const;
