/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

/**
 * Bearer token
 */
export type TokenStorageKeysAccessToken =
  (typeof TokenStorageKeysAccessToken)[keyof typeof TokenStorageKeysAccessToken];

 
export const TokenStorageKeysAccessToken = {
  labaccessToken: "lab.accessToken",
} as const;
