/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

/**
 * permissions 缓存(避免每次路由跳转都打 /auth/permissions)
 */
export type TokenStorageKeysPermissionsCache =
  (typeof TokenStorageKeysPermissionsCache)[keyof typeof TokenStorageKeysPermissionsCache];

export const TokenStorageKeysPermissionsCache = {
  labpermissions: "lab.permissions",
} as const;
