/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { UpdateParamInterfaceRequestConfig } from './updateParamInterfaceRequestConfig';

export interface UpdateParamInterfaceRequest {
  name?: string;
  componentPath?: string;
  description?: string;
  isOfficial?: boolean;
  sortOrder?: number;
  config?: UpdateParamInterfaceRequestConfig;
}
