/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */

export interface UpdateInspectionSpecialtyRequest {
  officialNo?: string;
  name?: string;
  isOfficial?: boolean;
  enabled?: boolean;
  sortOrder?: number;
}
