/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import type { UpdateSampleExtRequestExt } from "./updateSampleExtRequestExt";

export interface UpdateSampleExtRequest {
  ext: UpdateSampleExtRequestExt;
}
