/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateInspectionObjectRequest,
  CreateInspectionParameterRequest,
  CreateInspectionSpecialtyRequest,
  CreateInspectionStandardRequest,
  ErrorResponse,
  InspectionDictionaryListObjectParameterLinks200,
  InspectionDictionaryListObjectParameterLinksParams,
  InspectionDictionaryListObjectStandardLinks200,
  InspectionDictionaryListObjectStandardLinksParams,
  InspectionDictionaryListObjects200,
  InspectionDictionaryListObjectsParams,
  InspectionDictionaryListParameters200,
  InspectionDictionaryListParametersParams,
  InspectionDictionaryListSpecialties200,
  InspectionDictionaryListSpecialtiesParams,
  InspectionDictionaryListSpecialtyObjectLinks200,
  InspectionDictionaryListSpecialtyObjectLinksParams,
  InspectionDictionaryListStandardParameterLinks200,
  InspectionDictionaryListStandardParameterLinksParams,
  InspectionDictionaryListStandards200,
  InspectionDictionaryListStandardsParams,
  InspectionDictionaryUnlinkObjectParameterBody,
  InspectionDictionaryUnlinkObjectStandardBody,
  InspectionObject,
  InspectionParameter,
  InspectionSpecialty,
  InspectionStandard,
  ObjectParameterLink,
  ObjectStandardLink,
  SpecialtyObjectLink,
  StandardParameterLink,
  UpdateInspectionObjectRequest,
  UpdateInspectionParameterRequest,
  UpdateInspectionSpecialtyRequest,
  UpdateInspectionStandardRequest
} from '.././model';





export const inspectionDictionaryLinkObjectParameter = (
    objectParameterLink: ObjectParameterLink, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/api/inspection/links/object-parameter`,
      objectParameterLink,options
    );
  }



export const getInspectionDictionaryLinkObjectParameterMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryLinkObjectParameter>>, TError,{data: ObjectParameterLink}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryLinkObjectParameter>>, TError,{data: ObjectParameterLink}, TContext> => {

const mutationKey = ['inspectionDictionaryLinkObjectParameter'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryLinkObjectParameter>>, {data: ObjectParameterLink}> = (props) => {
          const {data} = props ?? {};

          return  inspectionDictionaryLinkObjectParameter(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryLinkObjectParameterMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryLinkObjectParameter>>>
    export type InspectionDictionaryLinkObjectParameterMutationBody = ObjectParameterLink
    export type InspectionDictionaryLinkObjectParameterMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryLinkObjectParameter = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryLinkObjectParameter>>, TError,{data: ObjectParameterLink}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryLinkObjectParameter>>,
        TError,
        {data: ObjectParameterLink},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryLinkObjectParameterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryUnlinkObjectParameter = (
    inspectionDictionaryUnlinkObjectParameterBody: InspectionDictionaryUnlinkObjectParameterBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/inspection/links/object-parameter`,{data:
      inspectionDictionaryUnlinkObjectParameterBody, ...options}
    );
  }



export const getInspectionDictionaryUnlinkObjectParameterMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUnlinkObjectParameter>>, TError,{data: InspectionDictionaryUnlinkObjectParameterBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUnlinkObjectParameter>>, TError,{data: InspectionDictionaryUnlinkObjectParameterBody}, TContext> => {

const mutationKey = ['inspectionDictionaryUnlinkObjectParameter'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryUnlinkObjectParameter>>, {data: InspectionDictionaryUnlinkObjectParameterBody}> = (props) => {
          const {data} = props ?? {};

          return  inspectionDictionaryUnlinkObjectParameter(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryUnlinkObjectParameterMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryUnlinkObjectParameter>>>
    export type InspectionDictionaryUnlinkObjectParameterMutationBody = InspectionDictionaryUnlinkObjectParameterBody
    export type InspectionDictionaryUnlinkObjectParameterMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryUnlinkObjectParameter = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUnlinkObjectParameter>>, TError,{data: InspectionDictionaryUnlinkObjectParameterBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryUnlinkObjectParameter>>,
        TError,
        {data: InspectionDictionaryUnlinkObjectParameterBody},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryUnlinkObjectParameterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryListObjectParameterLinks = (
    params?: InspectionDictionaryListObjectParameterLinksParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionDictionaryListObjectParameterLinks200>> => {
    
    
    return axios.default.get(
      `/api/inspection/links/object-parameter`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getInspectionDictionaryListObjectParameterLinksQueryKey = (params?: InspectionDictionaryListObjectParameterLinksParams,) => {
    return [
    `/api/inspection/links/object-parameter`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getInspectionDictionaryListObjectParameterLinksQueryOptions = <TData = Awaited<ReturnType<typeof inspectionDictionaryListObjectParameterLinks>>, TError = AxiosError<ErrorResponse>>(params?: InspectionDictionaryListObjectParameterLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListObjectParameterLinks>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInspectionDictionaryListObjectParameterLinksQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof inspectionDictionaryListObjectParameterLinks>>> = ({ signal }) => inspectionDictionaryListObjectParameterLinks(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListObjectParameterLinks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InspectionDictionaryListObjectParameterLinksQueryResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryListObjectParameterLinks>>>
export type InspectionDictionaryListObjectParameterLinksQueryError = AxiosError<ErrorResponse>


export function useInspectionDictionaryListObjectParameterLinks<TData = Awaited<ReturnType<typeof inspectionDictionaryListObjectParameterLinks>>, TError = AxiosError<ErrorResponse>>(
 params: undefined |  InspectionDictionaryListObjectParameterLinksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListObjectParameterLinks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof inspectionDictionaryListObjectParameterLinks>>,
          TError,
          Awaited<ReturnType<typeof inspectionDictionaryListObjectParameterLinks>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInspectionDictionaryListObjectParameterLinks<TData = Awaited<ReturnType<typeof inspectionDictionaryListObjectParameterLinks>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListObjectParameterLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListObjectParameterLinks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof inspectionDictionaryListObjectParameterLinks>>,
          TError,
          Awaited<ReturnType<typeof inspectionDictionaryListObjectParameterLinks>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInspectionDictionaryListObjectParameterLinks<TData = Awaited<ReturnType<typeof inspectionDictionaryListObjectParameterLinks>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListObjectParameterLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListObjectParameterLinks>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useInspectionDictionaryListObjectParameterLinks<TData = Awaited<ReturnType<typeof inspectionDictionaryListObjectParameterLinks>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListObjectParameterLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListObjectParameterLinks>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInspectionDictionaryListObjectParameterLinksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const inspectionDictionaryLinkObjectStandard = (
    objectStandardLink: ObjectStandardLink, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/api/inspection/links/object-standard`,
      objectStandardLink,options
    );
  }



export const getInspectionDictionaryLinkObjectStandardMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryLinkObjectStandard>>, TError,{data: ObjectStandardLink}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryLinkObjectStandard>>, TError,{data: ObjectStandardLink}, TContext> => {

const mutationKey = ['inspectionDictionaryLinkObjectStandard'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryLinkObjectStandard>>, {data: ObjectStandardLink}> = (props) => {
          const {data} = props ?? {};

          return  inspectionDictionaryLinkObjectStandard(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryLinkObjectStandardMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryLinkObjectStandard>>>
    export type InspectionDictionaryLinkObjectStandardMutationBody = ObjectStandardLink
    export type InspectionDictionaryLinkObjectStandardMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryLinkObjectStandard = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryLinkObjectStandard>>, TError,{data: ObjectStandardLink}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryLinkObjectStandard>>,
        TError,
        {data: ObjectStandardLink},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryLinkObjectStandardMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryUnlinkObjectStandard = (
    inspectionDictionaryUnlinkObjectStandardBody: InspectionDictionaryUnlinkObjectStandardBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/inspection/links/object-standard`,{data:
      inspectionDictionaryUnlinkObjectStandardBody, ...options}
    );
  }



export const getInspectionDictionaryUnlinkObjectStandardMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUnlinkObjectStandard>>, TError,{data: InspectionDictionaryUnlinkObjectStandardBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUnlinkObjectStandard>>, TError,{data: InspectionDictionaryUnlinkObjectStandardBody}, TContext> => {

const mutationKey = ['inspectionDictionaryUnlinkObjectStandard'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryUnlinkObjectStandard>>, {data: InspectionDictionaryUnlinkObjectStandardBody}> = (props) => {
          const {data} = props ?? {};

          return  inspectionDictionaryUnlinkObjectStandard(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryUnlinkObjectStandardMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryUnlinkObjectStandard>>>
    export type InspectionDictionaryUnlinkObjectStandardMutationBody = InspectionDictionaryUnlinkObjectStandardBody
    export type InspectionDictionaryUnlinkObjectStandardMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryUnlinkObjectStandard = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUnlinkObjectStandard>>, TError,{data: InspectionDictionaryUnlinkObjectStandardBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryUnlinkObjectStandard>>,
        TError,
        {data: InspectionDictionaryUnlinkObjectStandardBody},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryUnlinkObjectStandardMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryListObjectStandardLinks = (
    params?: InspectionDictionaryListObjectStandardLinksParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionDictionaryListObjectStandardLinks200>> => {
    
    
    return axios.default.get(
      `/api/inspection/links/object-standard`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getInspectionDictionaryListObjectStandardLinksQueryKey = (params?: InspectionDictionaryListObjectStandardLinksParams,) => {
    return [
    `/api/inspection/links/object-standard`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getInspectionDictionaryListObjectStandardLinksQueryOptions = <TData = Awaited<ReturnType<typeof inspectionDictionaryListObjectStandardLinks>>, TError = AxiosError<ErrorResponse>>(params?: InspectionDictionaryListObjectStandardLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListObjectStandardLinks>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInspectionDictionaryListObjectStandardLinksQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof inspectionDictionaryListObjectStandardLinks>>> = ({ signal }) => inspectionDictionaryListObjectStandardLinks(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListObjectStandardLinks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InspectionDictionaryListObjectStandardLinksQueryResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryListObjectStandardLinks>>>
export type InspectionDictionaryListObjectStandardLinksQueryError = AxiosError<ErrorResponse>


export function useInspectionDictionaryListObjectStandardLinks<TData = Awaited<ReturnType<typeof inspectionDictionaryListObjectStandardLinks>>, TError = AxiosError<ErrorResponse>>(
 params: undefined |  InspectionDictionaryListObjectStandardLinksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListObjectStandardLinks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof inspectionDictionaryListObjectStandardLinks>>,
          TError,
          Awaited<ReturnType<typeof inspectionDictionaryListObjectStandardLinks>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInspectionDictionaryListObjectStandardLinks<TData = Awaited<ReturnType<typeof inspectionDictionaryListObjectStandardLinks>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListObjectStandardLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListObjectStandardLinks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof inspectionDictionaryListObjectStandardLinks>>,
          TError,
          Awaited<ReturnType<typeof inspectionDictionaryListObjectStandardLinks>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInspectionDictionaryListObjectStandardLinks<TData = Awaited<ReturnType<typeof inspectionDictionaryListObjectStandardLinks>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListObjectStandardLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListObjectStandardLinks>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useInspectionDictionaryListObjectStandardLinks<TData = Awaited<ReturnType<typeof inspectionDictionaryListObjectStandardLinks>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListObjectStandardLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListObjectStandardLinks>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInspectionDictionaryListObjectStandardLinksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const inspectionDictionaryLinkSpecialtyObject = (
    specialtyObjectLink: SpecialtyObjectLink, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/api/inspection/links/specialty-object`,
      specialtyObjectLink,options
    );
  }



export const getInspectionDictionaryLinkSpecialtyObjectMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryLinkSpecialtyObject>>, TError,{data: SpecialtyObjectLink}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryLinkSpecialtyObject>>, TError,{data: SpecialtyObjectLink}, TContext> => {

const mutationKey = ['inspectionDictionaryLinkSpecialtyObject'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryLinkSpecialtyObject>>, {data: SpecialtyObjectLink}> = (props) => {
          const {data} = props ?? {};

          return  inspectionDictionaryLinkSpecialtyObject(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryLinkSpecialtyObjectMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryLinkSpecialtyObject>>>
    export type InspectionDictionaryLinkSpecialtyObjectMutationBody = SpecialtyObjectLink
    export type InspectionDictionaryLinkSpecialtyObjectMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryLinkSpecialtyObject = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryLinkSpecialtyObject>>, TError,{data: SpecialtyObjectLink}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryLinkSpecialtyObject>>,
        TError,
        {data: SpecialtyObjectLink},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryLinkSpecialtyObjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryUnlinkSpecialtyObject = (
    specialtyObjectLink: SpecialtyObjectLink, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/inspection/links/specialty-object`,{data:
      specialtyObjectLink, ...options}
    );
  }



export const getInspectionDictionaryUnlinkSpecialtyObjectMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUnlinkSpecialtyObject>>, TError,{data: SpecialtyObjectLink}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUnlinkSpecialtyObject>>, TError,{data: SpecialtyObjectLink}, TContext> => {

const mutationKey = ['inspectionDictionaryUnlinkSpecialtyObject'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryUnlinkSpecialtyObject>>, {data: SpecialtyObjectLink}> = (props) => {
          const {data} = props ?? {};

          return  inspectionDictionaryUnlinkSpecialtyObject(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryUnlinkSpecialtyObjectMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryUnlinkSpecialtyObject>>>
    export type InspectionDictionaryUnlinkSpecialtyObjectMutationBody = SpecialtyObjectLink
    export type InspectionDictionaryUnlinkSpecialtyObjectMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryUnlinkSpecialtyObject = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUnlinkSpecialtyObject>>, TError,{data: SpecialtyObjectLink}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryUnlinkSpecialtyObject>>,
        TError,
        {data: SpecialtyObjectLink},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryUnlinkSpecialtyObjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryListSpecialtyObjectLinks = (
    params?: InspectionDictionaryListSpecialtyObjectLinksParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionDictionaryListSpecialtyObjectLinks200>> => {
    
    
    return axios.default.get(
      `/api/inspection/links/specialty-object`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getInspectionDictionaryListSpecialtyObjectLinksQueryKey = (params?: InspectionDictionaryListSpecialtyObjectLinksParams,) => {
    return [
    `/api/inspection/links/specialty-object`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getInspectionDictionaryListSpecialtyObjectLinksQueryOptions = <TData = Awaited<ReturnType<typeof inspectionDictionaryListSpecialtyObjectLinks>>, TError = AxiosError<ErrorResponse>>(params?: InspectionDictionaryListSpecialtyObjectLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListSpecialtyObjectLinks>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInspectionDictionaryListSpecialtyObjectLinksQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof inspectionDictionaryListSpecialtyObjectLinks>>> = ({ signal }) => inspectionDictionaryListSpecialtyObjectLinks(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListSpecialtyObjectLinks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InspectionDictionaryListSpecialtyObjectLinksQueryResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryListSpecialtyObjectLinks>>>
export type InspectionDictionaryListSpecialtyObjectLinksQueryError = AxiosError<ErrorResponse>


export function useInspectionDictionaryListSpecialtyObjectLinks<TData = Awaited<ReturnType<typeof inspectionDictionaryListSpecialtyObjectLinks>>, TError = AxiosError<ErrorResponse>>(
 params: undefined |  InspectionDictionaryListSpecialtyObjectLinksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListSpecialtyObjectLinks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof inspectionDictionaryListSpecialtyObjectLinks>>,
          TError,
          Awaited<ReturnType<typeof inspectionDictionaryListSpecialtyObjectLinks>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInspectionDictionaryListSpecialtyObjectLinks<TData = Awaited<ReturnType<typeof inspectionDictionaryListSpecialtyObjectLinks>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListSpecialtyObjectLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListSpecialtyObjectLinks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof inspectionDictionaryListSpecialtyObjectLinks>>,
          TError,
          Awaited<ReturnType<typeof inspectionDictionaryListSpecialtyObjectLinks>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInspectionDictionaryListSpecialtyObjectLinks<TData = Awaited<ReturnType<typeof inspectionDictionaryListSpecialtyObjectLinks>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListSpecialtyObjectLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListSpecialtyObjectLinks>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useInspectionDictionaryListSpecialtyObjectLinks<TData = Awaited<ReturnType<typeof inspectionDictionaryListSpecialtyObjectLinks>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListSpecialtyObjectLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListSpecialtyObjectLinks>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInspectionDictionaryListSpecialtyObjectLinksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const inspectionDictionaryLinkStandardParameter = (
    standardParameterLink: StandardParameterLink, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/api/inspection/links/standard-parameter`,
      standardParameterLink,options
    );
  }



export const getInspectionDictionaryLinkStandardParameterMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryLinkStandardParameter>>, TError,{data: StandardParameterLink}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryLinkStandardParameter>>, TError,{data: StandardParameterLink}, TContext> => {

const mutationKey = ['inspectionDictionaryLinkStandardParameter'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryLinkStandardParameter>>, {data: StandardParameterLink}> = (props) => {
          const {data} = props ?? {};

          return  inspectionDictionaryLinkStandardParameter(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryLinkStandardParameterMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryLinkStandardParameter>>>
    export type InspectionDictionaryLinkStandardParameterMutationBody = StandardParameterLink
    export type InspectionDictionaryLinkStandardParameterMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryLinkStandardParameter = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryLinkStandardParameter>>, TError,{data: StandardParameterLink}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryLinkStandardParameter>>,
        TError,
        {data: StandardParameterLink},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryLinkStandardParameterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryUnlinkStandardParameter = (
    standardParameterLink: StandardParameterLink, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/inspection/links/standard-parameter`,{data:
      standardParameterLink, ...options}
    );
  }



export const getInspectionDictionaryUnlinkStandardParameterMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUnlinkStandardParameter>>, TError,{data: StandardParameterLink}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUnlinkStandardParameter>>, TError,{data: StandardParameterLink}, TContext> => {

const mutationKey = ['inspectionDictionaryUnlinkStandardParameter'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryUnlinkStandardParameter>>, {data: StandardParameterLink}> = (props) => {
          const {data} = props ?? {};

          return  inspectionDictionaryUnlinkStandardParameter(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryUnlinkStandardParameterMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryUnlinkStandardParameter>>>
    export type InspectionDictionaryUnlinkStandardParameterMutationBody = StandardParameterLink
    export type InspectionDictionaryUnlinkStandardParameterMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryUnlinkStandardParameter = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUnlinkStandardParameter>>, TError,{data: StandardParameterLink}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryUnlinkStandardParameter>>,
        TError,
        {data: StandardParameterLink},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryUnlinkStandardParameterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryListStandardParameterLinks = (
    params?: InspectionDictionaryListStandardParameterLinksParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionDictionaryListStandardParameterLinks200>> => {
    
    
    return axios.default.get(
      `/api/inspection/links/standard-parameter`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getInspectionDictionaryListStandardParameterLinksQueryKey = (params?: InspectionDictionaryListStandardParameterLinksParams,) => {
    return [
    `/api/inspection/links/standard-parameter`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getInspectionDictionaryListStandardParameterLinksQueryOptions = <TData = Awaited<ReturnType<typeof inspectionDictionaryListStandardParameterLinks>>, TError = AxiosError<ErrorResponse>>(params?: InspectionDictionaryListStandardParameterLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListStandardParameterLinks>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInspectionDictionaryListStandardParameterLinksQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof inspectionDictionaryListStandardParameterLinks>>> = ({ signal }) => inspectionDictionaryListStandardParameterLinks(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListStandardParameterLinks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InspectionDictionaryListStandardParameterLinksQueryResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryListStandardParameterLinks>>>
export type InspectionDictionaryListStandardParameterLinksQueryError = AxiosError<ErrorResponse>


export function useInspectionDictionaryListStandardParameterLinks<TData = Awaited<ReturnType<typeof inspectionDictionaryListStandardParameterLinks>>, TError = AxiosError<ErrorResponse>>(
 params: undefined |  InspectionDictionaryListStandardParameterLinksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListStandardParameterLinks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof inspectionDictionaryListStandardParameterLinks>>,
          TError,
          Awaited<ReturnType<typeof inspectionDictionaryListStandardParameterLinks>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInspectionDictionaryListStandardParameterLinks<TData = Awaited<ReturnType<typeof inspectionDictionaryListStandardParameterLinks>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListStandardParameterLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListStandardParameterLinks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof inspectionDictionaryListStandardParameterLinks>>,
          TError,
          Awaited<ReturnType<typeof inspectionDictionaryListStandardParameterLinks>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInspectionDictionaryListStandardParameterLinks<TData = Awaited<ReturnType<typeof inspectionDictionaryListStandardParameterLinks>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListStandardParameterLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListStandardParameterLinks>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useInspectionDictionaryListStandardParameterLinks<TData = Awaited<ReturnType<typeof inspectionDictionaryListStandardParameterLinks>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListStandardParameterLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListStandardParameterLinks>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInspectionDictionaryListStandardParameterLinksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const inspectionDictionaryListObjects = (
    params?: InspectionDictionaryListObjectsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionDictionaryListObjects200>> => {
    
    
    return axios.default.get(
      `/api/inspection/objects`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getInspectionDictionaryListObjectsQueryKey = (params?: InspectionDictionaryListObjectsParams,) => {
    return [
    `/api/inspection/objects`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getInspectionDictionaryListObjectsQueryOptions = <TData = Awaited<ReturnType<typeof inspectionDictionaryListObjects>>, TError = AxiosError<ErrorResponse>>(params?: InspectionDictionaryListObjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListObjects>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInspectionDictionaryListObjectsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof inspectionDictionaryListObjects>>> = ({ signal }) => inspectionDictionaryListObjects(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListObjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InspectionDictionaryListObjectsQueryResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryListObjects>>>
export type InspectionDictionaryListObjectsQueryError = AxiosError<ErrorResponse>


export function useInspectionDictionaryListObjects<TData = Awaited<ReturnType<typeof inspectionDictionaryListObjects>>, TError = AxiosError<ErrorResponse>>(
 params: undefined |  InspectionDictionaryListObjectsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListObjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof inspectionDictionaryListObjects>>,
          TError,
          Awaited<ReturnType<typeof inspectionDictionaryListObjects>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInspectionDictionaryListObjects<TData = Awaited<ReturnType<typeof inspectionDictionaryListObjects>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListObjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListObjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof inspectionDictionaryListObjects>>,
          TError,
          Awaited<ReturnType<typeof inspectionDictionaryListObjects>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInspectionDictionaryListObjects<TData = Awaited<ReturnType<typeof inspectionDictionaryListObjects>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListObjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListObjects>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useInspectionDictionaryListObjects<TData = Awaited<ReturnType<typeof inspectionDictionaryListObjects>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListObjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListObjects>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInspectionDictionaryListObjectsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const inspectionDictionaryCreateObject = (
    createInspectionObjectRequest: CreateInspectionObjectRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionObject>> => {
    
    
    return axios.default.post(
      `/api/inspection/objects`,
      createInspectionObjectRequest,options
    );
  }



export const getInspectionDictionaryCreateObjectMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryCreateObject>>, TError,{data: CreateInspectionObjectRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryCreateObject>>, TError,{data: CreateInspectionObjectRequest}, TContext> => {

const mutationKey = ['inspectionDictionaryCreateObject'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryCreateObject>>, {data: CreateInspectionObjectRequest}> = (props) => {
          const {data} = props ?? {};

          return  inspectionDictionaryCreateObject(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryCreateObjectMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryCreateObject>>>
    export type InspectionDictionaryCreateObjectMutationBody = CreateInspectionObjectRequest
    export type InspectionDictionaryCreateObjectMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryCreateObject = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryCreateObject>>, TError,{data: CreateInspectionObjectRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryCreateObject>>,
        TError,
        {data: CreateInspectionObjectRequest},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryCreateObjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryUpdateObject = (
    code: string,
    updateInspectionObjectRequest: UpdateInspectionObjectRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionObject>> => {
    
    
    return axios.default.put(
      `/api/inspection/objects/${code}`,
      updateInspectionObjectRequest,options
    );
  }



export const getInspectionDictionaryUpdateObjectMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUpdateObject>>, TError,{code: string;data: UpdateInspectionObjectRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUpdateObject>>, TError,{code: string;data: UpdateInspectionObjectRequest}, TContext> => {

const mutationKey = ['inspectionDictionaryUpdateObject'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryUpdateObject>>, {code: string;data: UpdateInspectionObjectRequest}> = (props) => {
          const {code,data} = props ?? {};

          return  inspectionDictionaryUpdateObject(code,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryUpdateObjectMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryUpdateObject>>>
    export type InspectionDictionaryUpdateObjectMutationBody = UpdateInspectionObjectRequest
    export type InspectionDictionaryUpdateObjectMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryUpdateObject = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUpdateObject>>, TError,{code: string;data: UpdateInspectionObjectRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryUpdateObject>>,
        TError,
        {code: string;data: UpdateInspectionObjectRequest},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryUpdateObjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryDeleteObject = (
    code: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/inspection/objects/${code}`,options
    );
  }



export const getInspectionDictionaryDeleteObjectMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryDeleteObject>>, TError,{code: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryDeleteObject>>, TError,{code: string}, TContext> => {

const mutationKey = ['inspectionDictionaryDeleteObject'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryDeleteObject>>, {code: string}> = (props) => {
          const {code} = props ?? {};

          return  inspectionDictionaryDeleteObject(code,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryDeleteObjectMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryDeleteObject>>>
    
    export type InspectionDictionaryDeleteObjectMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryDeleteObject = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryDeleteObject>>, TError,{code: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryDeleteObject>>,
        TError,
        {code: string},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryDeleteObjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryListParameters = (
    params?: InspectionDictionaryListParametersParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionDictionaryListParameters200>> => {
    
    
    return axios.default.get(
      `/api/inspection/parameters`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getInspectionDictionaryListParametersQueryKey = (params?: InspectionDictionaryListParametersParams,) => {
    return [
    `/api/inspection/parameters`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getInspectionDictionaryListParametersQueryOptions = <TData = Awaited<ReturnType<typeof inspectionDictionaryListParameters>>, TError = AxiosError<ErrorResponse>>(params?: InspectionDictionaryListParametersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListParameters>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInspectionDictionaryListParametersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof inspectionDictionaryListParameters>>> = ({ signal }) => inspectionDictionaryListParameters(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListParameters>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InspectionDictionaryListParametersQueryResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryListParameters>>>
export type InspectionDictionaryListParametersQueryError = AxiosError<ErrorResponse>


export function useInspectionDictionaryListParameters<TData = Awaited<ReturnType<typeof inspectionDictionaryListParameters>>, TError = AxiosError<ErrorResponse>>(
 params: undefined |  InspectionDictionaryListParametersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListParameters>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof inspectionDictionaryListParameters>>,
          TError,
          Awaited<ReturnType<typeof inspectionDictionaryListParameters>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInspectionDictionaryListParameters<TData = Awaited<ReturnType<typeof inspectionDictionaryListParameters>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListParametersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListParameters>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof inspectionDictionaryListParameters>>,
          TError,
          Awaited<ReturnType<typeof inspectionDictionaryListParameters>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInspectionDictionaryListParameters<TData = Awaited<ReturnType<typeof inspectionDictionaryListParameters>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListParametersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListParameters>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useInspectionDictionaryListParameters<TData = Awaited<ReturnType<typeof inspectionDictionaryListParameters>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListParametersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListParameters>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInspectionDictionaryListParametersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const inspectionDictionaryCreateParameter = (
    createInspectionParameterRequest: CreateInspectionParameterRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionParameter>> => {
    
    
    return axios.default.post(
      `/api/inspection/parameters`,
      createInspectionParameterRequest,options
    );
  }



export const getInspectionDictionaryCreateParameterMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryCreateParameter>>, TError,{data: CreateInspectionParameterRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryCreateParameter>>, TError,{data: CreateInspectionParameterRequest}, TContext> => {

const mutationKey = ['inspectionDictionaryCreateParameter'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryCreateParameter>>, {data: CreateInspectionParameterRequest}> = (props) => {
          const {data} = props ?? {};

          return  inspectionDictionaryCreateParameter(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryCreateParameterMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryCreateParameter>>>
    export type InspectionDictionaryCreateParameterMutationBody = CreateInspectionParameterRequest
    export type InspectionDictionaryCreateParameterMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryCreateParameter = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryCreateParameter>>, TError,{data: CreateInspectionParameterRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryCreateParameter>>,
        TError,
        {data: CreateInspectionParameterRequest},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryCreateParameterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryUpdateParameter = (
    code: string,
    updateInspectionParameterRequest: UpdateInspectionParameterRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionParameter>> => {
    
    
    return axios.default.put(
      `/api/inspection/parameters/${code}`,
      updateInspectionParameterRequest,options
    );
  }



export const getInspectionDictionaryUpdateParameterMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUpdateParameter>>, TError,{code: string;data: UpdateInspectionParameterRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUpdateParameter>>, TError,{code: string;data: UpdateInspectionParameterRequest}, TContext> => {

const mutationKey = ['inspectionDictionaryUpdateParameter'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryUpdateParameter>>, {code: string;data: UpdateInspectionParameterRequest}> = (props) => {
          const {code,data} = props ?? {};

          return  inspectionDictionaryUpdateParameter(code,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryUpdateParameterMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryUpdateParameter>>>
    export type InspectionDictionaryUpdateParameterMutationBody = UpdateInspectionParameterRequest
    export type InspectionDictionaryUpdateParameterMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryUpdateParameter = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUpdateParameter>>, TError,{code: string;data: UpdateInspectionParameterRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryUpdateParameter>>,
        TError,
        {code: string;data: UpdateInspectionParameterRequest},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryUpdateParameterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryDeleteParameter = (
    code: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/inspection/parameters/${code}`,options
    );
  }



export const getInspectionDictionaryDeleteParameterMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryDeleteParameter>>, TError,{code: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryDeleteParameter>>, TError,{code: string}, TContext> => {

const mutationKey = ['inspectionDictionaryDeleteParameter'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryDeleteParameter>>, {code: string}> = (props) => {
          const {code} = props ?? {};

          return  inspectionDictionaryDeleteParameter(code,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryDeleteParameterMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryDeleteParameter>>>
    
    export type InspectionDictionaryDeleteParameterMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryDeleteParameter = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryDeleteParameter>>, TError,{code: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryDeleteParameter>>,
        TError,
        {code: string},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryDeleteParameterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryListSpecialties = (
    params?: InspectionDictionaryListSpecialtiesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionDictionaryListSpecialties200>> => {
    
    
    return axios.default.get(
      `/api/inspection/specialties`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getInspectionDictionaryListSpecialtiesQueryKey = (params?: InspectionDictionaryListSpecialtiesParams,) => {
    return [
    `/api/inspection/specialties`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getInspectionDictionaryListSpecialtiesQueryOptions = <TData = Awaited<ReturnType<typeof inspectionDictionaryListSpecialties>>, TError = AxiosError<ErrorResponse>>(params?: InspectionDictionaryListSpecialtiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListSpecialties>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInspectionDictionaryListSpecialtiesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof inspectionDictionaryListSpecialties>>> = ({ signal }) => inspectionDictionaryListSpecialties(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListSpecialties>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InspectionDictionaryListSpecialtiesQueryResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryListSpecialties>>>
export type InspectionDictionaryListSpecialtiesQueryError = AxiosError<ErrorResponse>


export function useInspectionDictionaryListSpecialties<TData = Awaited<ReturnType<typeof inspectionDictionaryListSpecialties>>, TError = AxiosError<ErrorResponse>>(
 params: undefined |  InspectionDictionaryListSpecialtiesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListSpecialties>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof inspectionDictionaryListSpecialties>>,
          TError,
          Awaited<ReturnType<typeof inspectionDictionaryListSpecialties>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInspectionDictionaryListSpecialties<TData = Awaited<ReturnType<typeof inspectionDictionaryListSpecialties>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListSpecialtiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListSpecialties>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof inspectionDictionaryListSpecialties>>,
          TError,
          Awaited<ReturnType<typeof inspectionDictionaryListSpecialties>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInspectionDictionaryListSpecialties<TData = Awaited<ReturnType<typeof inspectionDictionaryListSpecialties>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListSpecialtiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListSpecialties>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useInspectionDictionaryListSpecialties<TData = Awaited<ReturnType<typeof inspectionDictionaryListSpecialties>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListSpecialtiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListSpecialties>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInspectionDictionaryListSpecialtiesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const inspectionDictionaryCreateSpecialty = (
    createInspectionSpecialtyRequest: CreateInspectionSpecialtyRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionSpecialty>> => {
    
    
    return axios.default.post(
      `/api/inspection/specialties`,
      createInspectionSpecialtyRequest,options
    );
  }



export const getInspectionDictionaryCreateSpecialtyMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryCreateSpecialty>>, TError,{data: CreateInspectionSpecialtyRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryCreateSpecialty>>, TError,{data: CreateInspectionSpecialtyRequest}, TContext> => {

const mutationKey = ['inspectionDictionaryCreateSpecialty'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryCreateSpecialty>>, {data: CreateInspectionSpecialtyRequest}> = (props) => {
          const {data} = props ?? {};

          return  inspectionDictionaryCreateSpecialty(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryCreateSpecialtyMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryCreateSpecialty>>>
    export type InspectionDictionaryCreateSpecialtyMutationBody = CreateInspectionSpecialtyRequest
    export type InspectionDictionaryCreateSpecialtyMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryCreateSpecialty = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryCreateSpecialty>>, TError,{data: CreateInspectionSpecialtyRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryCreateSpecialty>>,
        TError,
        {data: CreateInspectionSpecialtyRequest},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryCreateSpecialtyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryUpdateSpecialty = (
    code: string,
    updateInspectionSpecialtyRequest: UpdateInspectionSpecialtyRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionSpecialty>> => {
    
    
    return axios.default.put(
      `/api/inspection/specialties/${code}`,
      updateInspectionSpecialtyRequest,options
    );
  }



export const getInspectionDictionaryUpdateSpecialtyMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUpdateSpecialty>>, TError,{code: string;data: UpdateInspectionSpecialtyRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUpdateSpecialty>>, TError,{code: string;data: UpdateInspectionSpecialtyRequest}, TContext> => {

const mutationKey = ['inspectionDictionaryUpdateSpecialty'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryUpdateSpecialty>>, {code: string;data: UpdateInspectionSpecialtyRequest}> = (props) => {
          const {code,data} = props ?? {};

          return  inspectionDictionaryUpdateSpecialty(code,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryUpdateSpecialtyMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryUpdateSpecialty>>>
    export type InspectionDictionaryUpdateSpecialtyMutationBody = UpdateInspectionSpecialtyRequest
    export type InspectionDictionaryUpdateSpecialtyMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryUpdateSpecialty = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUpdateSpecialty>>, TError,{code: string;data: UpdateInspectionSpecialtyRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryUpdateSpecialty>>,
        TError,
        {code: string;data: UpdateInspectionSpecialtyRequest},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryUpdateSpecialtyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryDeleteSpecialty = (
    code: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/inspection/specialties/${code}`,options
    );
  }



export const getInspectionDictionaryDeleteSpecialtyMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryDeleteSpecialty>>, TError,{code: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryDeleteSpecialty>>, TError,{code: string}, TContext> => {

const mutationKey = ['inspectionDictionaryDeleteSpecialty'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryDeleteSpecialty>>, {code: string}> = (props) => {
          const {code} = props ?? {};

          return  inspectionDictionaryDeleteSpecialty(code,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryDeleteSpecialtyMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryDeleteSpecialty>>>
    
    export type InspectionDictionaryDeleteSpecialtyMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryDeleteSpecialty = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryDeleteSpecialty>>, TError,{code: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryDeleteSpecialty>>,
        TError,
        {code: string},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryDeleteSpecialtyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryListStandards = (
    params?: InspectionDictionaryListStandardsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionDictionaryListStandards200>> => {
    
    
    return axios.default.get(
      `/api/inspection/standards`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getInspectionDictionaryListStandardsQueryKey = (params?: InspectionDictionaryListStandardsParams,) => {
    return [
    `/api/inspection/standards`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getInspectionDictionaryListStandardsQueryOptions = <TData = Awaited<ReturnType<typeof inspectionDictionaryListStandards>>, TError = AxiosError<ErrorResponse>>(params?: InspectionDictionaryListStandardsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListStandards>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInspectionDictionaryListStandardsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof inspectionDictionaryListStandards>>> = ({ signal }) => inspectionDictionaryListStandards(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListStandards>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InspectionDictionaryListStandardsQueryResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryListStandards>>>
export type InspectionDictionaryListStandardsQueryError = AxiosError<ErrorResponse>


export function useInspectionDictionaryListStandards<TData = Awaited<ReturnType<typeof inspectionDictionaryListStandards>>, TError = AxiosError<ErrorResponse>>(
 params: undefined |  InspectionDictionaryListStandardsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListStandards>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof inspectionDictionaryListStandards>>,
          TError,
          Awaited<ReturnType<typeof inspectionDictionaryListStandards>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInspectionDictionaryListStandards<TData = Awaited<ReturnType<typeof inspectionDictionaryListStandards>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListStandardsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListStandards>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof inspectionDictionaryListStandards>>,
          TError,
          Awaited<ReturnType<typeof inspectionDictionaryListStandards>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInspectionDictionaryListStandards<TData = Awaited<ReturnType<typeof inspectionDictionaryListStandards>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListStandardsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListStandards>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useInspectionDictionaryListStandards<TData = Awaited<ReturnType<typeof inspectionDictionaryListStandards>>, TError = AxiosError<ErrorResponse>>(
 params?: InspectionDictionaryListStandardsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inspectionDictionaryListStandards>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInspectionDictionaryListStandardsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const inspectionDictionaryCreateStandard = (
    createInspectionStandardRequest: CreateInspectionStandardRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionStandard>> => {
    
    
    return axios.default.post(
      `/api/inspection/standards`,
      createInspectionStandardRequest,options
    );
  }



export const getInspectionDictionaryCreateStandardMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryCreateStandard>>, TError,{data: CreateInspectionStandardRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryCreateStandard>>, TError,{data: CreateInspectionStandardRequest}, TContext> => {

const mutationKey = ['inspectionDictionaryCreateStandard'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryCreateStandard>>, {data: CreateInspectionStandardRequest}> = (props) => {
          const {data} = props ?? {};

          return  inspectionDictionaryCreateStandard(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryCreateStandardMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryCreateStandard>>>
    export type InspectionDictionaryCreateStandardMutationBody = CreateInspectionStandardRequest
    export type InspectionDictionaryCreateStandardMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryCreateStandard = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryCreateStandard>>, TError,{data: CreateInspectionStandardRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryCreateStandard>>,
        TError,
        {data: CreateInspectionStandardRequest},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryCreateStandardMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryUpdateStandard = (
    code: string,
    updateInspectionStandardRequest: UpdateInspectionStandardRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionStandard>> => {
    
    
    return axios.default.put(
      `/api/inspection/standards/${code}`,
      updateInspectionStandardRequest,options
    );
  }



export const getInspectionDictionaryUpdateStandardMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUpdateStandard>>, TError,{code: string;data: UpdateInspectionStandardRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUpdateStandard>>, TError,{code: string;data: UpdateInspectionStandardRequest}, TContext> => {

const mutationKey = ['inspectionDictionaryUpdateStandard'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryUpdateStandard>>, {code: string;data: UpdateInspectionStandardRequest}> = (props) => {
          const {code,data} = props ?? {};

          return  inspectionDictionaryUpdateStandard(code,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryUpdateStandardMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryUpdateStandard>>>
    export type InspectionDictionaryUpdateStandardMutationBody = UpdateInspectionStandardRequest
    export type InspectionDictionaryUpdateStandardMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryUpdateStandard = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryUpdateStandard>>, TError,{code: string;data: UpdateInspectionStandardRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryUpdateStandard>>,
        TError,
        {code: string;data: UpdateInspectionStandardRequest},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryUpdateStandardMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inspectionDictionaryDeleteStandard = (
    code: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/inspection/standards/${code}`,options
    );
  }



export const getInspectionDictionaryDeleteStandardMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryDeleteStandard>>, TError,{code: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryDeleteStandard>>, TError,{code: string}, TContext> => {

const mutationKey = ['inspectionDictionaryDeleteStandard'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inspectionDictionaryDeleteStandard>>, {code: string}> = (props) => {
          const {code} = props ?? {};

          return  inspectionDictionaryDeleteStandard(code,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InspectionDictionaryDeleteStandardMutationResult = NonNullable<Awaited<ReturnType<typeof inspectionDictionaryDeleteStandard>>>
    
    export type InspectionDictionaryDeleteStandardMutationError = AxiosError<ErrorResponse>

    export const useInspectionDictionaryDeleteStandard = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inspectionDictionaryDeleteStandard>>, TError,{code: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inspectionDictionaryDeleteStandard>>,
        TError,
        {code: string},
        TContext
      > => {

      const mutationOptions = getInspectionDictionaryDeleteStandardMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    