/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  CreateTechnicalRequirementRequest,
  ErrorResponse,
  TechnicalRequirement,
  TechnicalRequirementsListTechnicalRequirementsParams,
  UpdateTechnicalRequirementRequest,
} from ".././model";

export const technicalRequirementsListTechnicalRequirements = (
  params?: TechnicalRequirementsListTechnicalRequirementsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TechnicalRequirement[]>> => {
  return axios.default.get(`/api/technical-requirements`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getTechnicalRequirementsListTechnicalRequirementsQueryKey = (
  params?: TechnicalRequirementsListTechnicalRequirementsParams,
) => {
  return [`/api/technical-requirements`, ...(params ? [params] : [])] as const;
};

export const getTechnicalRequirementsListTechnicalRequirementsQueryOptions = <
  TData = Awaited<ReturnType<typeof technicalRequirementsListTechnicalRequirements>>,
  TError = AxiosError<ErrorResponse>,
>(
  params?: TechnicalRequirementsListTechnicalRequirementsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof technicalRequirementsListTechnicalRequirements>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getTechnicalRequirementsListTechnicalRequirementsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof technicalRequirementsListTechnicalRequirements>>
  > = ({ signal }) =>
    technicalRequirementsListTechnicalRequirements(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof technicalRequirementsListTechnicalRequirements>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TechnicalRequirementsListTechnicalRequirementsQueryResult = NonNullable<
  Awaited<ReturnType<typeof technicalRequirementsListTechnicalRequirements>>
>;
export type TechnicalRequirementsListTechnicalRequirementsQueryError =
  AxiosError<ErrorResponse>;

export function useTechnicalRequirementsListTechnicalRequirements<
  TData = Awaited<ReturnType<typeof technicalRequirementsListTechnicalRequirements>>,
  TError = AxiosError<ErrorResponse>,
>(
  params: undefined | TechnicalRequirementsListTechnicalRequirementsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof technicalRequirementsListTechnicalRequirements>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof technicalRequirementsListTechnicalRequirements>>,
          TError,
          Awaited<ReturnType<typeof technicalRequirementsListTechnicalRequirements>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTechnicalRequirementsListTechnicalRequirements<
  TData = Awaited<ReturnType<typeof technicalRequirementsListTechnicalRequirements>>,
  TError = AxiosError<ErrorResponse>,
>(
  params?: TechnicalRequirementsListTechnicalRequirementsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof technicalRequirementsListTechnicalRequirements>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof technicalRequirementsListTechnicalRequirements>>,
          TError,
          Awaited<ReturnType<typeof technicalRequirementsListTechnicalRequirements>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTechnicalRequirementsListTechnicalRequirements<
  TData = Awaited<ReturnType<typeof technicalRequirementsListTechnicalRequirements>>,
  TError = AxiosError<ErrorResponse>,
>(
  params?: TechnicalRequirementsListTechnicalRequirementsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof technicalRequirementsListTechnicalRequirements>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useTechnicalRequirementsListTechnicalRequirements<
  TData = Awaited<ReturnType<typeof technicalRequirementsListTechnicalRequirements>>,
  TError = AxiosError<ErrorResponse>,
>(
  params?: TechnicalRequirementsListTechnicalRequirementsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof technicalRequirementsListTechnicalRequirements>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTechnicalRequirementsListTechnicalRequirementsQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const technicalRequirementsCreateTechnicalRequirement = (
  createTechnicalRequirementRequest: CreateTechnicalRequirementRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TechnicalRequirement>> => {
  return axios.default.post(
    `/api/technical-requirements`,
    createTechnicalRequirementRequest,
    options,
  );
};

export const getTechnicalRequirementsCreateTechnicalRequirementMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof technicalRequirementsCreateTechnicalRequirement>>,
    TError,
    { data: CreateTechnicalRequirementRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof technicalRequirementsCreateTechnicalRequirement>>,
  TError,
  { data: CreateTechnicalRequirementRequest },
  TContext
> => {
  const mutationKey = ["technicalRequirementsCreateTechnicalRequirement"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof technicalRequirementsCreateTechnicalRequirement>>,
    { data: CreateTechnicalRequirementRequest }
  > = (props) => {
    const { data } = props ?? {};

    return technicalRequirementsCreateTechnicalRequirement(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TechnicalRequirementsCreateTechnicalRequirementMutationResult = NonNullable<
  Awaited<ReturnType<typeof technicalRequirementsCreateTechnicalRequirement>>
>;
export type TechnicalRequirementsCreateTechnicalRequirementMutationBody =
  CreateTechnicalRequirementRequest;
export type TechnicalRequirementsCreateTechnicalRequirementMutationError =
  AxiosError<ErrorResponse>;

export const useTechnicalRequirementsCreateTechnicalRequirement = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof technicalRequirementsCreateTechnicalRequirement>>,
      TError,
      { data: CreateTechnicalRequirementRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof technicalRequirementsCreateTechnicalRequirement>>,
  TError,
  { data: CreateTechnicalRequirementRequest },
  TContext
> => {
  const mutationOptions =
    getTechnicalRequirementsCreateTechnicalRequirementMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const technicalRequirementsGetTechnicalRequirement = (
  inspectionObjectCode: string,
  inspectionParameterCode: string,
  judgmentStandardCode: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TechnicalRequirement>> => {
  return axios.default.get(
    `/api/technical-requirements/${inspectionObjectCode}/${inspectionParameterCode}/${judgmentStandardCode}`,
    options,
  );
};

export const getTechnicalRequirementsGetTechnicalRequirementQueryKey = (
  inspectionObjectCode?: string,
  inspectionParameterCode?: string,
  judgmentStandardCode?: string,
) => {
  return [
    `/api/technical-requirements/${inspectionObjectCode}/${inspectionParameterCode}/${judgmentStandardCode}`,
  ] as const;
};

export const getTechnicalRequirementsGetTechnicalRequirementQueryOptions = <
  TData = Awaited<ReturnType<typeof technicalRequirementsGetTechnicalRequirement>>,
  TError = AxiosError<ErrorResponse>,
>(
  inspectionObjectCode: string,
  inspectionParameterCode: string,
  judgmentStandardCode: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof technicalRequirementsGetTechnicalRequirement>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getTechnicalRequirementsGetTechnicalRequirementQueryKey(
      inspectionObjectCode,
      inspectionParameterCode,
      judgmentStandardCode,
    );

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof technicalRequirementsGetTechnicalRequirement>>
  > = ({ signal }) =>
    technicalRequirementsGetTechnicalRequirement(
      inspectionObjectCode,
      inspectionParameterCode,
      judgmentStandardCode,
      { signal, ...axiosOptions },
    );

  return {
    queryKey,
    queryFn,
    enabled: !!(inspectionObjectCode && inspectionParameterCode && judgmentStandardCode),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof technicalRequirementsGetTechnicalRequirement>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TechnicalRequirementsGetTechnicalRequirementQueryResult = NonNullable<
  Awaited<ReturnType<typeof technicalRequirementsGetTechnicalRequirement>>
>;
export type TechnicalRequirementsGetTechnicalRequirementQueryError =
  AxiosError<ErrorResponse>;

export function useTechnicalRequirementsGetTechnicalRequirement<
  TData = Awaited<ReturnType<typeof technicalRequirementsGetTechnicalRequirement>>,
  TError = AxiosError<ErrorResponse>,
>(
  inspectionObjectCode: string,
  inspectionParameterCode: string,
  judgmentStandardCode: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof technicalRequirementsGetTechnicalRequirement>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof technicalRequirementsGetTechnicalRequirement>>,
          TError,
          Awaited<ReturnType<typeof technicalRequirementsGetTechnicalRequirement>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTechnicalRequirementsGetTechnicalRequirement<
  TData = Awaited<ReturnType<typeof technicalRequirementsGetTechnicalRequirement>>,
  TError = AxiosError<ErrorResponse>,
>(
  inspectionObjectCode: string,
  inspectionParameterCode: string,
  judgmentStandardCode: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof technicalRequirementsGetTechnicalRequirement>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof technicalRequirementsGetTechnicalRequirement>>,
          TError,
          Awaited<ReturnType<typeof technicalRequirementsGetTechnicalRequirement>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTechnicalRequirementsGetTechnicalRequirement<
  TData = Awaited<ReturnType<typeof technicalRequirementsGetTechnicalRequirement>>,
  TError = AxiosError<ErrorResponse>,
>(
  inspectionObjectCode: string,
  inspectionParameterCode: string,
  judgmentStandardCode: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof technicalRequirementsGetTechnicalRequirement>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useTechnicalRequirementsGetTechnicalRequirement<
  TData = Awaited<ReturnType<typeof technicalRequirementsGetTechnicalRequirement>>,
  TError = AxiosError<ErrorResponse>,
>(
  inspectionObjectCode: string,
  inspectionParameterCode: string,
  judgmentStandardCode: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof technicalRequirementsGetTechnicalRequirement>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTechnicalRequirementsGetTechnicalRequirementQueryOptions(
    inspectionObjectCode,
    inspectionParameterCode,
    judgmentStandardCode,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const technicalRequirementsUpdateTechnicalRequirement = (
  inspectionObjectCode: string,
  inspectionParameterCode: string,
  judgmentStandardCode: string,
  updateTechnicalRequirementRequest: UpdateTechnicalRequirementRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TechnicalRequirement>> => {
  return axios.default.put(
    `/api/technical-requirements/${inspectionObjectCode}/${inspectionParameterCode}/${judgmentStandardCode}`,
    updateTechnicalRequirementRequest,
    options,
  );
};

export const getTechnicalRequirementsUpdateTechnicalRequirementMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof technicalRequirementsUpdateTechnicalRequirement>>,
    TError,
    {
      inspectionObjectCode: string;
      inspectionParameterCode: string;
      judgmentStandardCode: string;
      data: UpdateTechnicalRequirementRequest;
    },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof technicalRequirementsUpdateTechnicalRequirement>>,
  TError,
  {
    inspectionObjectCode: string;
    inspectionParameterCode: string;
    judgmentStandardCode: string;
    data: UpdateTechnicalRequirementRequest;
  },
  TContext
> => {
  const mutationKey = ["technicalRequirementsUpdateTechnicalRequirement"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof technicalRequirementsUpdateTechnicalRequirement>>,
    {
      inspectionObjectCode: string;
      inspectionParameterCode: string;
      judgmentStandardCode: string;
      data: UpdateTechnicalRequirementRequest;
    }
  > = (props) => {
    const { inspectionObjectCode, inspectionParameterCode, judgmentStandardCode, data } =
      props ?? {};

    return technicalRequirementsUpdateTechnicalRequirement(
      inspectionObjectCode,
      inspectionParameterCode,
      judgmentStandardCode,
      data,
      axiosOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type TechnicalRequirementsUpdateTechnicalRequirementMutationResult = NonNullable<
  Awaited<ReturnType<typeof technicalRequirementsUpdateTechnicalRequirement>>
>;
export type TechnicalRequirementsUpdateTechnicalRequirementMutationBody =
  UpdateTechnicalRequirementRequest;
export type TechnicalRequirementsUpdateTechnicalRequirementMutationError =
  AxiosError<ErrorResponse>;

export const useTechnicalRequirementsUpdateTechnicalRequirement = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof technicalRequirementsUpdateTechnicalRequirement>>,
      TError,
      {
        inspectionObjectCode: string;
        inspectionParameterCode: string;
        judgmentStandardCode: string;
        data: UpdateTechnicalRequirementRequest;
      },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof technicalRequirementsUpdateTechnicalRequirement>>,
  TError,
  {
    inspectionObjectCode: string;
    inspectionParameterCode: string;
    judgmentStandardCode: string;
    data: UpdateTechnicalRequirementRequest;
  },
  TContext
> => {
  const mutationOptions =
    getTechnicalRequirementsUpdateTechnicalRequirementMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const technicalRequirementsDeleteTechnicalRequirement = (
  inspectionObjectCode: string,
  inspectionParameterCode: string,
  judgmentStandardCode: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.default.delete(
    `/api/technical-requirements/${inspectionObjectCode}/${inspectionParameterCode}/${judgmentStandardCode}`,
    options,
  );
};

export const getTechnicalRequirementsDeleteTechnicalRequirementMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof technicalRequirementsDeleteTechnicalRequirement>>,
    TError,
    {
      inspectionObjectCode: string;
      inspectionParameterCode: string;
      judgmentStandardCode: string;
    },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof technicalRequirementsDeleteTechnicalRequirement>>,
  TError,
  {
    inspectionObjectCode: string;
    inspectionParameterCode: string;
    judgmentStandardCode: string;
  },
  TContext
> => {
  const mutationKey = ["technicalRequirementsDeleteTechnicalRequirement"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof technicalRequirementsDeleteTechnicalRequirement>>,
    {
      inspectionObjectCode: string;
      inspectionParameterCode: string;
      judgmentStandardCode: string;
    }
  > = (props) => {
    const { inspectionObjectCode, inspectionParameterCode, judgmentStandardCode } =
      props ?? {};

    return technicalRequirementsDeleteTechnicalRequirement(
      inspectionObjectCode,
      inspectionParameterCode,
      judgmentStandardCode,
      axiosOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type TechnicalRequirementsDeleteTechnicalRequirementMutationResult = NonNullable<
  Awaited<ReturnType<typeof technicalRequirementsDeleteTechnicalRequirement>>
>;

export type TechnicalRequirementsDeleteTechnicalRequirementMutationError =
  AxiosError<ErrorResponse>;

export const useTechnicalRequirementsDeleteTechnicalRequirement = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof technicalRequirementsDeleteTechnicalRequirement>>,
      TError,
      {
        inspectionObjectCode: string;
        inspectionParameterCode: string;
        judgmentStandardCode: string;
      },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof technicalRequirementsDeleteTechnicalRequirement>>,
  TError,
  {
    inspectionObjectCode: string;
    inspectionParameterCode: string;
    judgmentStandardCode: string;
  },
  TContext
> => {
  const mutationOptions =
    getTechnicalRequirementsDeleteTechnicalRequirementMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
