/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateSampleRequest,
  ErrorResponse,
  Sample,
  SamplesListSamples200,
  SamplesListSamplesParams,
  UpdateSampleExtRequest,
  UpdateSampleRequest
} from '.././model';





export const samplesListSamples = (
    params?: SamplesListSamplesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SamplesListSamples200>> => {
    
    
    return axios.default.get(
      `/api/samples`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getSamplesListSamplesQueryKey = (params?: SamplesListSamplesParams,) => {
    return [
    `/api/samples`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSamplesListSamplesQueryOptions = <TData = Awaited<ReturnType<typeof samplesListSamples>>, TError = AxiosError<ErrorResponse>>(params?: SamplesListSamplesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof samplesListSamples>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSamplesListSamplesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof samplesListSamples>>> = ({ signal }) => samplesListSamples(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof samplesListSamples>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SamplesListSamplesQueryResult = NonNullable<Awaited<ReturnType<typeof samplesListSamples>>>
export type SamplesListSamplesQueryError = AxiosError<ErrorResponse>


export function useSamplesListSamples<TData = Awaited<ReturnType<typeof samplesListSamples>>, TError = AxiosError<ErrorResponse>>(
 params: undefined |  SamplesListSamplesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof samplesListSamples>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof samplesListSamples>>,
          TError,
          Awaited<ReturnType<typeof samplesListSamples>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSamplesListSamples<TData = Awaited<ReturnType<typeof samplesListSamples>>, TError = AxiosError<ErrorResponse>>(
 params?: SamplesListSamplesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof samplesListSamples>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof samplesListSamples>>,
          TError,
          Awaited<ReturnType<typeof samplesListSamples>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSamplesListSamples<TData = Awaited<ReturnType<typeof samplesListSamples>>, TError = AxiosError<ErrorResponse>>(
 params?: SamplesListSamplesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof samplesListSamples>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSamplesListSamples<TData = Awaited<ReturnType<typeof samplesListSamples>>, TError = AxiosError<ErrorResponse>>(
 params?: SamplesListSamplesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof samplesListSamples>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSamplesListSamplesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const samplesCreateSample = (
    createSampleRequest: CreateSampleRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Sample>> => {
    
    
    return axios.default.post(
      `/api/samples`,
      createSampleRequest,options
    );
  }



export const getSamplesCreateSampleMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof samplesCreateSample>>, TError,{data: CreateSampleRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof samplesCreateSample>>, TError,{data: CreateSampleRequest}, TContext> => {

const mutationKey = ['samplesCreateSample'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof samplesCreateSample>>, {data: CreateSampleRequest}> = (props) => {
          const {data} = props ?? {};

          return  samplesCreateSample(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SamplesCreateSampleMutationResult = NonNullable<Awaited<ReturnType<typeof samplesCreateSample>>>
    export type SamplesCreateSampleMutationBody = CreateSampleRequest
    export type SamplesCreateSampleMutationError = AxiosError<ErrorResponse>

    export const useSamplesCreateSample = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof samplesCreateSample>>, TError,{data: CreateSampleRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof samplesCreateSample>>,
        TError,
        {data: CreateSampleRequest},
        TContext
      > => {

      const mutationOptions = getSamplesCreateSampleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const samplesGetSample = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Sample>> => {
    
    
    return axios.default.get(
      `/api/samples/${id}`,options
    );
  }




export const getSamplesGetSampleQueryKey = (id?: string,) => {
    return [
    `/api/samples/${id}`
    ] as const;
    }

    
export const getSamplesGetSampleQueryOptions = <TData = Awaited<ReturnType<typeof samplesGetSample>>, TError = AxiosError<ErrorResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof samplesGetSample>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSamplesGetSampleQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof samplesGetSample>>> = ({ signal }) => samplesGetSample(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof samplesGetSample>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SamplesGetSampleQueryResult = NonNullable<Awaited<ReturnType<typeof samplesGetSample>>>
export type SamplesGetSampleQueryError = AxiosError<ErrorResponse>


export function useSamplesGetSample<TData = Awaited<ReturnType<typeof samplesGetSample>>, TError = AxiosError<ErrorResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof samplesGetSample>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof samplesGetSample>>,
          TError,
          Awaited<ReturnType<typeof samplesGetSample>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSamplesGetSample<TData = Awaited<ReturnType<typeof samplesGetSample>>, TError = AxiosError<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof samplesGetSample>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof samplesGetSample>>,
          TError,
          Awaited<ReturnType<typeof samplesGetSample>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSamplesGetSample<TData = Awaited<ReturnType<typeof samplesGetSample>>, TError = AxiosError<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof samplesGetSample>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSamplesGetSample<TData = Awaited<ReturnType<typeof samplesGetSample>>, TError = AxiosError<ErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof samplesGetSample>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSamplesGetSampleQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const samplesUpdateSample = (
    id: string,
    updateSampleRequest: UpdateSampleRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Sample>> => {
    
    
    return axios.default.put(
      `/api/samples/${id}`,
      updateSampleRequest,options
    );
  }



export const getSamplesUpdateSampleMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof samplesUpdateSample>>, TError,{id: string;data: UpdateSampleRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof samplesUpdateSample>>, TError,{id: string;data: UpdateSampleRequest}, TContext> => {

const mutationKey = ['samplesUpdateSample'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof samplesUpdateSample>>, {id: string;data: UpdateSampleRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  samplesUpdateSample(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SamplesUpdateSampleMutationResult = NonNullable<Awaited<ReturnType<typeof samplesUpdateSample>>>
    export type SamplesUpdateSampleMutationBody = UpdateSampleRequest
    export type SamplesUpdateSampleMutationError = AxiosError<ErrorResponse>

    export const useSamplesUpdateSample = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof samplesUpdateSample>>, TError,{id: string;data: UpdateSampleRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof samplesUpdateSample>>,
        TError,
        {id: string;data: UpdateSampleRequest},
        TContext
      > => {

      const mutationOptions = getSamplesUpdateSampleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const samplesDeleteSample = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/samples/${id}`,options
    );
  }



export const getSamplesDeleteSampleMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof samplesDeleteSample>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof samplesDeleteSample>>, TError,{id: string}, TContext> => {

const mutationKey = ['samplesDeleteSample'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof samplesDeleteSample>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  samplesDeleteSample(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SamplesDeleteSampleMutationResult = NonNullable<Awaited<ReturnType<typeof samplesDeleteSample>>>
    
    export type SamplesDeleteSampleMutationError = AxiosError<ErrorResponse>

    export const useSamplesDeleteSample = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof samplesDeleteSample>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof samplesDeleteSample>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getSamplesDeleteSampleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const samplesUpdateSampleExt = (
    id: string,
    updateSampleExtRequest: UpdateSampleExtRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Sample>> => {
    
    
    return axios.default.put(
      `/api/samples/${id}/ext`,
      updateSampleExtRequest,options
    );
  }



export const getSamplesUpdateSampleExtMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof samplesUpdateSampleExt>>, TError,{id: string;data: UpdateSampleExtRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof samplesUpdateSampleExt>>, TError,{id: string;data: UpdateSampleExtRequest}, TContext> => {

const mutationKey = ['samplesUpdateSampleExt'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof samplesUpdateSampleExt>>, {id: string;data: UpdateSampleExtRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  samplesUpdateSampleExt(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SamplesUpdateSampleExtMutationResult = NonNullable<Awaited<ReturnType<typeof samplesUpdateSampleExt>>>
    export type SamplesUpdateSampleExtMutationBody = UpdateSampleExtRequest
    export type SamplesUpdateSampleExtMutationError = AxiosError<ErrorResponse>

    export const useSamplesUpdateSampleExt = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof samplesUpdateSampleExt>>, TError,{id: string;data: UpdateSampleExtRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof samplesUpdateSampleExt>>,
        TError,
        {id: string;data: UpdateSampleExtRequest},
        TContext
      > => {

      const mutationOptions = getSamplesUpdateSampleExtMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    