/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
export interface AssignTaskRequest {
  assigneeId?: string;
  assigneeName?: string;
  plannedTestDate?: string;
}

/**
 * AuthContext 数据契约。方法(login/logout/refresh/switchTenant/hasPermission/onChange)由消费方实现,TS 签名见 .state/decision-log.md §2.2
 */
export interface AuthContext {
  /** 当前 auth 状态 */
  state: AuthState;
}

export type AuthHeaderKind = typeof AuthHeaderKind[keyof typeof AuthHeaderKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthHeaderKind = {
  Authorization: 'Authorization',
  'X-Auth-Token': 'X-Auth-Token',
} as const;

/**
 * auth 状态机 4 态。Vue: pinia store / React: Context;两侧实现可同构
 */
export type AuthState = AuthStateIdle | AuthStateAnonymous | AuthStateAwaitingTenant | AuthStateAuthenticated;

export type AuthStateAnonymousKind = typeof AuthStateAnonymousKind[keyof typeof AuthStateAnonymousKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthStateAnonymousKind = {
  anonymous: 'anonymous',
} as const;

export type AuthStateAnonymousValueKind = typeof AuthStateAnonymousValueKind[keyof typeof AuthStateAnonymousValueKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthStateAnonymousValueKind = {
  anonymous: 'anonymous',
} as const;

export type AuthStateAnonymousValue = {
  kind: AuthStateAnonymousValueKind;
};

export interface AuthStateAnonymous {
  kind: AuthStateAnonymousKind;
  value: AuthStateAnonymousValue;
}

export type AuthStateAuthenticatedKind = typeof AuthStateAuthenticatedKind[keyof typeof AuthStateAuthenticatedKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthStateAuthenticatedKind = {
  authenticated: 'authenticated',
} as const;

export type AuthStateAuthenticatedValueKind = typeof AuthStateAuthenticatedValueKind[keyof typeof AuthStateAuthenticatedValueKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthStateAuthenticatedValueKind = {
  authenticated: 'authenticated',
} as const;

export type AuthStateAuthenticatedValue = {
  kind: AuthStateAuthenticatedValueKind;
  user: CurrentUser;
  tenant: MyTenant;
  permissions: string[];
  /** unix ms */
  tokenExpiresAt: number;
};

export interface AuthStateAuthenticated {
  kind: AuthStateAuthenticatedKind;
  value: AuthStateAuthenticatedValue;
}

export type AuthStateAwaitingTenantKind = typeof AuthStateAwaitingTenantKind[keyof typeof AuthStateAwaitingTenantKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthStateAwaitingTenantKind = {
  awaiting_tenant: 'awaiting_tenant',
} as const;

export type AuthStateAwaitingTenantValueKind = typeof AuthStateAwaitingTenantValueKind[keyof typeof AuthStateAwaitingTenantValueKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthStateAwaitingTenantValueKind = {
  awaiting_tenant: 'awaiting_tenant',
} as const;

export type AuthStateAwaitingTenantValue = {
  kind: AuthStateAwaitingTenantValueKind;
  user: CurrentUser;
  tenants: MyTenant[];
};

export interface AuthStateAwaitingTenant {
  kind: AuthStateAwaitingTenantKind;
  value: AuthStateAwaitingTenantValue;
}

export type AuthStateIdleKind = typeof AuthStateIdleKind[keyof typeof AuthStateIdleKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthStateIdleKind = {
  idle: 'idle',
} as const;

export type AuthStateIdleValueKind = typeof AuthStateIdleValueKind[keyof typeof AuthStateIdleValueKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthStateIdleValueKind = {
  idle: 'idle',
} as const;

export type AuthStateIdleValue = {
  kind: AuthStateIdleValueKind;
};

export interface AuthStateIdle {
  kind: AuthStateIdleKind;
  value: AuthStateIdleValue;
}

/**
 * 4-backend 运行时切换配置。运行时由消费方仓各自实现(React Context / Vue pinia store)
 */
export interface BackendConfig {
  /** 槽位标识,必须是 BackendId 之一 */
  id: BackendId;
  /** 显示名(MSW Mock / Next.js API / Spring Boot / ASP.NET Core) */
  label: string;
  /** baseUrl 的展示值,例如 'http://localhost:3000/api' */
  baseUrl: string;
  /** token 头:Bearer 走 Authorization,部分老后端用 X-Auth-Token */
  authHeader: AuthHeaderKind;
  /** SSO 回调路径(仅启用 SSO 的后端填写) */
  ssoCallbackPath?: string;
  /** 能力矩阵 */
  features: BackendFeatures;
}

/**
 * 后端能力矩阵
 */
export interface BackendFeatures {
  /** 是否启用 SSO 跳转(msw=false / nextjs=true / springboot/aspnetcore 视实现) */
  sso: boolean;
  /** 是否对接真实数据库(vs mock seed) */
  realDb: boolean;
}

/**
 * 4 个槽位;id 锁定,避免拼写漂移
 */
export type BackendId = typeof BackendId[keyof typeof BackendId];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BackendId = {
  msw: 'msw',
  nextjs: 'nextjs',
  springboot: 'springboot',
  aspnetcore: 'aspnetcore',
} as const;

/**
 * 运行时注册表:当前激活 + 可切列表。切换/订阅方法由消费方实现,TS 签名见 .state/decision-log.md §2.1
 */
export interface BackendRegistry {
  /** 当前激活后端 */
  active: BackendId;
  /** 可切换列表(通常包含全部 4 个槽位) */
  available: BackendConfig[];
}

export type CalculationAlgorithmType = typeof CalculationAlgorithmType[keyof typeof CalculationAlgorithmType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CalculationAlgorithmType = {
  simple_avg: 'simple_avg',
  compressive_strength: 'compressive_strength',
  flexural_strength: 'flexural_strength',
  steel_tensile: 'steel_tensile',
  formula: 'formula',
  manual: 'manual',
  auto_calc_ratio: 'auto_calc_ratio',
} as const;

export interface CalculationRule {
  inspectionObjectCode: string;
  inspectionParameterCode: string;
  testingStandardCode?: string;
  reportNameCode?: string;
  algorithmType: CalculationAlgorithmType;
  specimenCount: number;
  formula?: string;
  conditions?: string;
  roundingRule?: string;
  remark?: string;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface Contract {
  id: string;
  tenantId: string;
  contractCode: string;
  clientUnit: string;
  projectName: string;
  projectLocation?: string;
  constructionUnit: string;
  inspectionSpecialtyCode?: string;
  buildingUnit?: string;
  supervisorUnit?: string;
  inspectionPerson?: string;
  inspectionPhone?: string;
  witnessUnit: string;
  witness: string;
  witnessPhone?: string;
  contactPerson?: string;
  contactPhone?: string;
  entrustedDate?: string;
  status: ContractStatus;
  createdAt: string;
  updatedAt: string;
}

export type ContractStatus = typeof ContractStatus[keyof typeof ContractStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContractStatus = {
  active: 'active',
  archived: 'archived',
} as const;

export interface CreateCalculationRuleRequest {
  inspectionObjectCode: string;
  inspectionParameterCode: string;
  testingStandardCode?: string;
  reportNameCode?: string;
  algorithmType?: CalculationAlgorithmType;
  specimenCount?: number;
  formula?: string;
  conditions?: string;
  roundingRule?: string;
  remark?: string;
  sortOrder?: number;
}

export interface CreateCatalogEntryRequest {
  code: string;
  inspectionObjectCode?: string;
  name: string;
  remark?: string;
  sortOrder?: number;
}

export interface CreateContractRequest {
  contractCode: string;
  clientUnit: string;
  projectName: string;
  projectLocation?: string;
  constructionUnit: string;
  inspectionSpecialtyCode?: string;
  buildingUnit?: string;
  supervisorUnit?: string;
  inspectionPerson?: string;
  inspectionPhone?: string;
  witnessUnit: string;
  witness: string;
  witnessPhone?: string;
  contactPerson?: string;
  contactPhone?: string;
  entrustedDate?: string;
  status?: ContractStatus;
}

export interface CreateInspectionObjectRequest {
  code: string;
  inspectionSpecialtyCode: string;
  sourceProjectNo: string;
  sourceProjectName: string;
  name: string;
  isOptionalForQualification?: boolean;
  isOfficial?: boolean;
  enabled?: boolean;
  sortOrder?: number;
}

export interface CreateInspectionParameterRequest {
  code: string;
  name: string;
  rawName: string;
  canonicalName: string;
  methodText?: string;
  aliases?: string[];
  unit?: string;
  sourceType?: InspectionParameterSourceType;
  sortOrder?: number;
}

export interface CreateInspectionReportNameRequest {
  code: string;
  name: string;
  fullName?: string;
  templatePath?: string;
  summaryName?: string;
  extFields?: ExtFieldDef[];
  description?: string;
  sortOrder?: number;
}

export interface CreateInspectionSpecialtyRequest {
  code: string;
  officialNo: string;
  name: string;
  isOfficial?: boolean;
  enabled?: boolean;
  sortOrder?: number;
}

export interface CreateInspectionStandardRequest {
  code: string;
  name: string;
  version?: string;
  status?: InspectionStandardStatus;
  sourceDocumentId?: string;
  sourceHash?: string;
  sortOrder?: number;
}

export type CreateParamInterfaceRequestConfig = {[key: string]: unknown};

export interface CreateParamInterfaceRequest {
  code: string;
  name?: string;
  componentPath: string;
  description?: string;
  isOfficial?: boolean;
  sortOrder?: number;
  config?: CreateParamInterfaceRequestConfig;
}

export interface CreateSampleReceiptRequest {
  contractId: string;
  commissionCode: string;
  commissionDate: string;
  commissionRegisterCode?: string;
  commissionRegisterDate?: string;
  categoryCode: string;
  projectName?: string;
  clientUnit?: string;
  buildingUnit?: string;
  supervisorUnit?: string;
  constructionUnit?: string;
  witnessUnit?: string;
  samplingLocation?: string;
  witness?: string;
  witnessPhone?: string;
  inspector?: string;
  inspectorPhone?: string;
  receivedBy: string;
  sampleSource: string;
  testCategory: string;
  testEnvironment?: string;
  mainEquipment?: string;
  testOperator?: string;
  testStartDate?: string;
  testEndDate?: string;
  originalRecordNo?: string;
  remark?: string;
  judgmentBasis?: string[];
  testingBasis?: string[];
  testParameters?: string[];
}

export type CreateSampleRequestExt = {[key: string]: string};

export interface CreateSampleRequest {
  receiptId: string;
  sampleCode: string;
  sampleName?: string;
  model?: string;
  specification?: string;
  grade?: string;
  brand?: string;
  manufacturer?: string;
  structuralPart?: string;
  representQuantity?: string;
  sampleQuantity?: string;
  batchNumber?: string;
  supplyUnit?: string;
  arrivalDate?: string;
  samplingDate?: string;
  curingCondition?: string;
  age?: string;
  ext?: CreateSampleRequestExt;
  remark?: string;
}

export interface CreateTechnicalRequirementRequest {
  inspectionObjectCode: string;
  inspectionParameterCode: string;
  judgmentStandardCode: string;
  conditions?: string;
  valueType?: RequirementValueType;
  minValue?: number;
  maxValue?: number;
  targetValue?: string;
  expression?: string;
  unit?: string;
  comparison?: RequirementComparison;
  judgmentMode?: RequirementJudgmentMode;
  verificationStatus?: RequirementVerificationStatus;
  clause?: string;
  sourcePage?: number;
  sourceHash?: string;
  brand?: string;
  model?: string;
  grade?: string;
  spec?: string;
  sieve?: string;
  remark?: string;
  sortOrder?: number;
}

export interface CreateTestRecordRequest {
  sampleId: string;
  parameterCode: string;
  standardCode?: string;
  requirementCode?: string;
  requirement: string;
  result: string;
  verdict?: string;
}

export interface CurrentUser {
  id: string;
  username: string;
  displayName?: string;
  roleCode?: string;
}

export interface CurrentUserSession {
  user: CurrentUser;
  tenants: MyTenant[];
  currentTenantId?: string;
}

export type DashboardStatsReportCountByStatus = {
  draft: number;
  reviewing: number;
  issued: number;
};

export interface DashboardStats {
  contractCount: number;
  receiptCount: number;
  sampleCount: number;
  reportCountByStatus: DashboardStatsReportCountByStatus;
  pendingTaskCount: number;
}

export type ErrorResponseDetails = {[key: string]: unknown};

export interface ErrorResponse {
  code: string;
  message: string;
  details?: ErrorResponseDetails;
}

export interface ExtFieldDef {
  key: string;
  label: string;
  type: ExtFieldDefType;
  required?: boolean;
  options?: string[];
  tag?: string;
  source?: ExtFieldDefSource;
}

export type ExtFieldDefSource = typeof ExtFieldDefSource[keyof typeof ExtFieldDefSource];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExtFieldDefSource = {
  sample: 'sample',
  receipt: 'receipt',
} as const;

export type ExtFieldDefType = typeof ExtFieldDefType[keyof typeof ExtFieldDefType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExtFieldDefType = {
  text: 'text',
  number: 'number',
  date: 'date',
  select: 'select',
} as const;

export type FlowAction = typeof FlowAction[keyof typeof FlowAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FlowAction = {
  submit: 'submit',
  return: 'return',
  withdraw: 'withdraw',
} as const;

export interface FlowActionRequest {
  ids: string[];
  action: FlowAction;
  operator: string;
  reason?: string;
}

export interface FlowActionResult {
  id: string;
  ok: boolean;
  message?: string;
  flowStatus?: FlowStatus;
}

export interface FlowHistoryEntry {
  action: FlowAction;
  from: FlowStatus;
  to: FlowStatus;
  operator: string;
  at: string;
  reason?: string;
}

export type FlowStatus = typeof FlowStatus[keyof typeof FlowStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FlowStatus = {
  receiving: 'receiving',
  task_assignment: 'task_assignment',
  data_entry: 'data_entry',
  review: 'review',
  approval: 'approval',
  issuance: 'issuance',
  archived: 'archived',
  completed: 'completed',
} as const;

export interface FrontendBindMetaFrontendBindSnapshot {
  registry: BackendRegistry;
  authContext: AuthContext;
  tokenKeys: TokenStorageKeys;
}

export interface InspectionBrand {
  code: string;
  tenantId: string;
  inspectionObjectCode?: string;
  name: string;
  remark?: string;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface InspectionGrade {
  code: string;
  tenantId: string;
  inspectionObjectCode?: string;
  name: string;
  remark?: string;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface InspectionModel {
  code: string;
  tenantId: string;
  inspectionObjectCode?: string;
  name: string;
  remark?: string;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface InspectionObject {
  code: string;
  inspectionSpecialtyCode: string;
  sourceProjectNo: string;
  sourceProjectName: string;
  name: string;
  isOptionalForQualification: boolean;
  isOfficial: boolean;
  enabled: boolean;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface InspectionParameter {
  code: string;
  name: string;
  rawName: string;
  canonicalName: string;
  methodText?: string;
  aliases: string[];
  unit?: string;
  sourceType: InspectionParameterSourceType;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export type InspectionParameterSourceType = typeof InspectionParameterSourceType[keyof typeof InspectionParameterSourceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InspectionParameterSourceType = {
  official: 'official',
  custom: 'custom',
} as const;

export interface InspectionReportName {
  code: string;
  name: string;
  fullName?: string;
  templatePath?: string;
  summaryName?: string;
  extFields?: ExtFieldDef[];
  description?: string;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface InspectionSpec {
  code: string;
  tenantId: string;
  inspectionObjectCode?: string;
  name: string;
  remark?: string;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface InspectionSpecialty {
  code: string;
  officialNo: string;
  name: string;
  isOfficial: boolean;
  enabled: boolean;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface InspectionStandard {
  code: string;
  name: string;
  version?: string;
  status: InspectionStandardStatus;
  sourceDocumentId?: string;
  sourceHash?: string;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export type InspectionStandardRole = typeof InspectionStandardRole[keyof typeof InspectionStandardRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InspectionStandardRole = {
  TESTING: 'TESTING',
  JUDGMENT: 'JUDGMENT',
} as const;

export type InspectionStandardStatus = typeof InspectionStandardStatus[keyof typeof InspectionStandardStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InspectionStandardStatus = {
  active: 'active',
  superseded: 'superseded',
  draft: 'draft',
} as const;

export interface LoginRequest {
  username: string;
  password: string;
}

export interface LoginResponse {
  token: string;
  refreshToken?: string;
  user: CurrentUser;
  tenants: MyTenant[];
}

export interface MenuNode {
  id: string;
  label: string;
  path?: string;
  icon?: string;
  children?: MenuNode[];
}

export interface MyTenant {
  tenantId: string;
  code: string;
  name: string;
  roleIds: string[];
}

export interface ObjectParameterLink {
  inspectionObjectCode: string;
  inspectionParameterCode: string;
  qualificationLevel: QualificationLevel;
  sourcePage?: number;
  remark?: string;
}

export interface ObjectReportNameLink {
  inspectionObjectCode: string;
  reportNameCode: string;
  remark?: string;
}

export interface ObjectStandardLink {
  inspectionObjectCode: string;
  inspectionStandardCode: string;
  role: InspectionStandardRole;
  remark?: string;
}

export type ParamInterfaceConfig = {[key: string]: unknown};

export interface ParamInterface {
  code: string;
  name?: string;
  componentPath: string;
  description?: string;
  isOfficial?: boolean;
  sortOrder: number;
  config?: ParamInterfaceConfig;
  createdAt: string;
  updatedAt: string;
}

export type ParamInterfaceLinkConfig = {[key: string]: unknown};

export interface ParamInterfaceLink {
  inspectionParameterCode: string;
  paramInterfaceCode: string;
  reportNameCode?: string;
  config?: ParamInterfaceLinkConfig;
}

export interface PermissionSet {
  permissions: string[];
}

export type QualificationLevel = typeof QualificationLevel[keyof typeof QualificationLevel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QualificationLevel = {
  QUALIFIED: 'QUALIFIED',
  RESTRICTED: 'RESTRICTED',
} as const;

export type ReceiptResult = typeof ReceiptResult[keyof typeof ReceiptResult];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReceiptResult = {
  pass: 'pass',
  fail: 'fail',
  '': '',
} as const;

export interface RefreshTokenRequest {
  refreshToken: string;
}

export interface ReportNameParameterLink {
  reportNameCode: string;
  inspectionParameterCode: string;
  remark?: string;
}

export interface ReportNameStandardLink {
  reportNameCode: string;
  inspectionStandardCode: string;
  role: InspectionStandardRole;
  remark?: string;
}

export type RequirementComparison = typeof RequirementComparison[keyof typeof RequirementComparison];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequirementComparison = {
  '≥': '≥',
  '≤': '≤',
  '=': '=',
  range: 'range',
  eq: 'eq',
} as const;

export type RequirementJudgmentMode = typeof RequirementJudgmentMode[keyof typeof RequirementJudgmentMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequirementJudgmentMode = {
  automatic: 'automatic',
  manual: 'manual',
} as const;

export type RequirementValueType = typeof RequirementValueType[keyof typeof RequirementValueType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequirementValueType = {
  numeric: 'numeric',
  string: 'string',
  range: 'range',
  formula: 'formula',
  manual: 'manual',
} as const;

export type RequirementVerificationStatus = typeof RequirementVerificationStatus[keyof typeof RequirementVerificationStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequirementVerificationStatus = {
  draft: 'draft',
  reviewed: 'reviewed',
  verified: 'verified',
  rejected: 'rejected',
} as const;

export type SampleExt = {[key: string]: string};

export interface Sample {
  id: string;
  tenantId: string;
  receiptId: string;
  sampleCode: string;
  sampleName?: string;
  model?: string;
  specification?: string;
  grade?: string;
  brand?: string;
  manufacturer?: string;
  structuralPart?: string;
  representQuantity?: string;
  sampleQuantity?: string;
  batchNumber?: string;
  supplyUnit?: string;
  arrivalDate?: string;
  samplingDate?: string;
  curingCondition?: string;
  age?: string;
  ext: SampleExt;
  remark?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SampleReceipt {
  id: string;
  tenantId: string;
  contractId: string;
  commissionCode: string;
  commissionDate: string;
  commissionRegisterCode?: string;
  commissionRegisterDate?: string;
  categoryCode: string;
  projectName?: string;
  clientUnit?: string;
  buildingUnit?: string;
  supervisorUnit?: string;
  constructionUnit?: string;
  witnessUnit?: string;
  samplingLocation?: string;
  witness?: string;
  witnessPhone?: string;
  inspector?: string;
  inspectorPhone?: string;
  receivedBy: string;
  sampleSource: string;
  testCategory: string;
  testEnvironment?: string;
  mainEquipment?: string;
  testOperator?: string;
  testStartDate?: string;
  testEndDate?: string;
  originalRecordNo?: string;
  remark?: string;
  judgmentBasis?: string[];
  testingBasis?: string[];
  testParameters?: string[];
  flowStatus: FlowStatus;
  flowHistory: FlowHistoryEntry[];
  lastSubmittedBy?: string;
  assigneeId?: string;
  assigneeName?: string;
  plannedTestDate?: string;
  reportCode?: string;
  reportDate?: string;
  conclusion?: string;
  result?: ReceiptResult;
  issuedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SpecialtyObjectLink {
  inspectionSpecialtyCode: string;
  inspectionObjectCode: string;
  remark?: string;
}

export interface SsoCallbackRequest {
  code: string;
  state: string;
}

export interface SsoRedirect {
  authorizeUrl: string;
  state: string;
}

export interface StandardParameterLink {
  inspectionStandardCode: string;
  inspectionParameterCode: string;
}

export interface SummaryColumn {
  key: string;
  label: string;
}

export type SummaryDataRowsItem = {[key: string]: string};

export interface SummaryData {
  summaryName: string;
  columns: SummaryColumn[];
  rows: SummaryDataRowsItem[];
}

export interface SwitchTenantRequest {
  tenantId: string;
}

export interface TechnicalRequirement {
  tenantId: string;
  inspectionObjectCode: string;
  inspectionParameterCode: string;
  judgmentStandardCode: string;
  conditions?: string;
  valueType: RequirementValueType;
  minValue?: number;
  maxValue?: number;
  targetValue?: string;
  expression?: string;
  unit?: string;
  comparison: RequirementComparison;
  judgmentMode: RequirementJudgmentMode;
  verificationStatus: RequirementVerificationStatus;
  clause?: string;
  sourcePage?: number;
  sourceHash?: string;
  brand?: string;
  model?: string;
  grade?: string;
  spec?: string;
  sieve?: string;
  remark?: string;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface TestRecord {
  id: string;
  tenantId: string;
  sampleId: string;
  parameterCode: string;
  standardCode?: string;
  requirementCode?: string;
  requirement: string;
  result: string;
  verdict?: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Bearer token
 */
export type TokenStorageKeysAccessToken = typeof TokenStorageKeysAccessToken[keyof typeof TokenStorageKeysAccessToken];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TokenStorageKeysAccessToken = {
  labaccessToken: 'lab.accessToken',
} as const;

/**
 * refresh token(与 accessToken 分存,便于隔离 XSS 影响面)
 */
export type TokenStorageKeysRefreshToken = typeof TokenStorageKeysRefreshToken[keyof typeof TokenStorageKeysRefreshToken];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TokenStorageKeysRefreshToken = {
  labrefreshToken: 'lab.refreshToken',
} as const;

/**
 * 当前选中租户 ID(authenticated 态缓存)
 */
export type TokenStorageKeysActiveTenantId = typeof TokenStorageKeysActiveTenantId[keyof typeof TokenStorageKeysActiveTenantId];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TokenStorageKeysActiveTenantId = {
  labactiveTenantId: 'lab.activeTenantId',
} as const;

/**
 * 当前激活后端槽位(用于跨刷新记忆)
 */
export type TokenStorageKeysActiveBackend = typeof TokenStorageKeysActiveBackend[keyof typeof TokenStorageKeysActiveBackend];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TokenStorageKeysActiveBackend = {
  labactiveBackend: 'lab.activeBackend',
} as const;

/**
 * permissions 缓存(避免每次路由跳转都打 /auth/permissions)
 */
export type TokenStorageKeysPermissionsCache = typeof TokenStorageKeysPermissionsCache[keyof typeof TokenStorageKeysPermissionsCache];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TokenStorageKeysPermissionsCache = {
  labpermissions: 'lab.permissions',
} as const;

/**
 * 前端持久化 key 命名约定;后端契约不感知,但前端实现必须遵守
 */
export interface TokenStorageKeys {
  /** Bearer token */
  accessToken: TokenStorageKeysAccessToken;
  /** refresh token(与 accessToken 分存,便于隔离 XSS 影响面) */
  refreshToken: TokenStorageKeysRefreshToken;
  /** 当前选中租户 ID(authenticated 态缓存) */
  activeTenantId: TokenStorageKeysActiveTenantId;
  /** 当前激活后端槽位(用于跨刷新记忆) */
  activeBackend: TokenStorageKeysActiveBackend;
  /** permissions 缓存(避免每次路由跳转都打 /auth/permissions) */
  permissionsCache: TokenStorageKeysPermissionsCache;
}

export interface UpdateCalculationRuleRequest {
  testingStandardCode?: string;
  reportNameCode?: string;
  algorithmType?: CalculationAlgorithmType;
  specimenCount?: number;
  formula?: string;
  conditions?: string;
  roundingRule?: string;
  remark?: string;
  sortOrder?: number;
}

export interface UpdateCatalogEntryRequest {
  inspectionObjectCode?: string;
  name?: string;
  remark?: string;
  sortOrder?: number;
}

export interface UpdateContractRequest {
  contractCode?: string;
  clientUnit?: string;
  projectName?: string;
  projectLocation?: string;
  constructionUnit?: string;
  inspectionSpecialtyCode?: string;
  buildingUnit?: string;
  supervisorUnit?: string;
  inspectionPerson?: string;
  inspectionPhone?: string;
  witnessUnit?: string;
  witness?: string;
  witnessPhone?: string;
  contactPerson?: string;
  contactPhone?: string;
  entrustedDate?: string;
  status?: ContractStatus;
}

export interface UpdateInspectionObjectRequest {
  inspectionSpecialtyCode?: string;
  sourceProjectNo?: string;
  sourceProjectName?: string;
  name?: string;
  isOptionalForQualification?: boolean;
  isOfficial?: boolean;
  enabled?: boolean;
  sortOrder?: number;
}

export interface UpdateInspectionParameterRequest {
  name?: string;
  rawName?: string;
  canonicalName?: string;
  methodText?: string;
  aliases?: string[];
  unit?: string;
  sourceType?: InspectionParameterSourceType;
  sortOrder?: number;
}

export interface UpdateInspectionReportNameRequest {
  name?: string;
  fullName?: string;
  templatePath?: string;
  summaryName?: string;
  extFields?: ExtFieldDef[];
  description?: string;
  sortOrder?: number;
}

export interface UpdateInspectionSpecialtyRequest {
  officialNo?: string;
  name?: string;
  isOfficial?: boolean;
  enabled?: boolean;
  sortOrder?: number;
}

export interface UpdateInspectionStandardRequest {
  name?: string;
  version?: string;
  status?: InspectionStandardStatus;
  sourceDocumentId?: string;
  sourceHash?: string;
  sortOrder?: number;
}

export type UpdateParamInterfaceRequestConfig = {[key: string]: unknown};

export interface UpdateParamInterfaceRequest {
  name?: string;
  componentPath?: string;
  description?: string;
  isOfficial?: boolean;
  sortOrder?: number;
  config?: UpdateParamInterfaceRequestConfig;
}

export interface UpdateSampleReceiptRequest {
  contractId?: string;
  commissionCode?: string;
  commissionDate?: string;
  commissionRegisterCode?: string;
  commissionRegisterDate?: string;
  categoryCode?: string;
  projectName?: string;
  clientUnit?: string;
  buildingUnit?: string;
  supervisorUnit?: string;
  constructionUnit?: string;
  witnessUnit?: string;
  samplingLocation?: string;
  witness?: string;
  witnessPhone?: string;
  inspector?: string;
  inspectorPhone?: string;
  receivedBy?: string;
  sampleSource?: string;
  testCategory?: string;
  testEnvironment?: string;
  mainEquipment?: string;
  testOperator?: string;
  testStartDate?: string;
  testEndDate?: string;
  originalRecordNo?: string;
  remark?: string;
  judgmentBasis?: string[];
  testingBasis?: string[];
  testParameters?: string[];
}

export type UpdateSampleRequestExt = {[key: string]: string};

export interface UpdateSampleRequest {
  receiptId?: string;
  sampleCode?: string;
  sampleName?: string;
  model?: string;
  specification?: string;
  grade?: string;
  brand?: string;
  manufacturer?: string;
  structuralPart?: string;
  representQuantity?: string;
  sampleQuantity?: string;
  batchNumber?: string;
  supplyUnit?: string;
  arrivalDate?: string;
  samplingDate?: string;
  curingCondition?: string;
  age?: string;
  ext?: UpdateSampleRequestExt;
  remark?: string;
}

export interface UpdateTechnicalRequirementRequest {
  conditions?: string;
  valueType?: RequirementValueType;
  minValue?: number;
  maxValue?: number;
  targetValue?: string;
  expression?: string;
  unit?: string;
  comparison?: RequirementComparison;
  judgmentMode?: RequirementJudgmentMode;
  verificationStatus?: RequirementVerificationStatus;
  clause?: string;
  sourcePage?: number;
  sourceHash?: string;
  brand?: string;
  model?: string;
  grade?: string;
  spec?: string;
  sieve?: string;
  remark?: string;
  sortOrder?: number;
}

export interface UpdateTestRecordRequest {
  sampleId?: string;
  parameterCode?: string;
  standardCode?: string;
  requirementCode?: string;
  requirement?: string;
  result?: string;
  verdict?: string;
}

export type AuthLogoutBody = {
  token: string;
};

export type AuthSsoAuthorizeParams = {
redirect: string;
};

export type CalculationRulesListCalculationRulesParams = {
inspectionObjectCode?: string;
inspectionParameterCode?: string;
};

export type CatalogListBrandsParams = {
inspectionObjectCode?: string;
keyword?: string;
};

export type CatalogListGradesParams = {
inspectionObjectCode?: string;
keyword?: string;
};

export type CatalogListModelsParams = {
inspectionObjectCode?: string;
keyword?: string;
};

export type CatalogListSpecsParams = {
inspectionObjectCode?: string;
keyword?: string;
};

export type ContractsListContractsParams = {
page?: number;
pageSize?: number;
keyword?: string;
status?: ContractStatus;
};

export type ContractsListContracts200 = {
  items: Contract[];
  page: number;
  pageSize: number;
  total: number;
};

export type InspectionDictionaryUnlinkObjectParameterBody = {
  inspectionObjectCode: string;
  inspectionParameterCode: string;
};

export type InspectionDictionaryUnlinkObjectStandardBody = {
  inspectionObjectCode: string;
  inspectionStandardCode: string;
  role: InspectionStandardRole;
};

export type InspectionDictionaryListObjectsParams = {
inspectionSpecialtyCode?: string;
keyword?: string;
};

export type InspectionDictionaryListParametersParams = {
keyword?: string;
sourceType?: InspectionParameterSourceType;
};

export type InspectionDictionaryListSpecialtiesParams = {
keyword?: string;
};

export type InspectionDictionaryListStandardsParams = {
keyword?: string;
status?: InspectionStandardStatus;
};

export type ParamInterfacesListParamInterfacesParams = {
keyword?: string;
};

export type ParamInterfacesUnlinkParamInterfaceBody = {
  inspectionParameterCode: string;
  paramInterfaceCode: string;
};

export type ReceiptsListReceiptsParams = {
page?: number;
pageSize?: number;
keyword?: string;
contractId?: string;
flowStatus?: FlowStatus;
};

export type ReceiptsListReceipts200 = {
  items: SampleReceipt[];
  page: number;
  pageSize: number;
  total: number;
};

export type ReportFlowListFlowQueueParams = {
stage: FlowStatus;
page?: number;
pageSize?: number;
};

export type ReportFlowListFlowQueue200 = {
  items: SampleReceipt[];
  page: number;
  pageSize: number;
  total: number;
};

export type ReportNamesListReportNamesParams = {
keyword?: string;
};

export type ReportNamesUnlinkObjectReportNameBody = {
  inspectionObjectCode: string;
  reportNameCode: string;
};

export type ReportNamesUnlinkReportNameParameterBody = {
  reportNameCode: string;
  inspectionParameterCode: string;
};

export type ReportNamesUnlinkReportNameStandardBody = {
  reportNameCode: string;
  inspectionStandardCode: string;
  role: InspectionStandardRole;
};

export type SamplesListSamplesParams = {
page?: number;
pageSize?: number;
receiptId?: string;
keyword?: string;
};

export type SamplesListSamples200 = {
  items: Sample[];
  page: number;
  pageSize: number;
  total: number;
};

export type SummaryGetReportSummaryParams = {
categoryCode?: string;
dateFrom?: string;
dateTo?: string;
};

export type TechnicalRequirementsListTechnicalRequirementsParams = {
inspectionObjectCode?: string;
inspectionParameterCode?: string;
judgmentStandardCode?: string;
verificationStatus?: RequirementVerificationStatus;
};

export type TestRecordsListTestRecordsParams = {
page?: number;
pageSize?: number;
sampleId?: string;
parameterCode?: string;
};

export type TestRecordsListTestRecords200 = {
  items: TestRecord[];
  page: number;
  pageSize: number;
  total: number;
};

export type TestRecordsSetVerdictBody = {
  verdict: string;
};

