/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
export interface AssignTaskRequest {
  assigneeId?: string;
  assigneeName?: string;
  plannedTestDate?: string;
}

export interface Contract {
  id: string;
  contractCode: string;
  clientUnit: string;
  projectName: string;
  projectLocation?: string;
  constructionUnit: string;
  inspectionSpecialtyCode?: string;
  buildingUnit?: string;
  supervisorUnit?: string;
  inspectionPerson?: string;
  inspectionPhone?: string;
  witnessUnit: string;
  witness: string;
  witnessPhone?: string;
  contactPerson?: string;
  contactPhone?: string;
  entrustedDate?: string;
  status: ContractStatus;
  createdAt: string;
  updatedAt: string;
}

export type ContractStatus = typeof ContractStatus[keyof typeof ContractStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContractStatus = {
  active: 'active',
  archived: 'archived',
} as const;

export interface CreateCatalogEntryRequest {
  code: string;
  inspectionObjectCode?: string;
  name: string;
  remark?: string;
  sortOrder?: number;
}

export interface CreateContractRequest {
  contractCode: string;
  clientUnit: string;
  projectName: string;
  projectLocation?: string;
  constructionUnit: string;
  inspectionSpecialtyCode?: string;
  buildingUnit?: string;
  supervisorUnit?: string;
  inspectionPerson?: string;
  inspectionPhone?: string;
  witnessUnit: string;
  witness: string;
  witnessPhone?: string;
  contactPerson?: string;
  contactPhone?: string;
  entrustedDate?: string;
  status?: ContractStatus;
}

export type CreateSampleReceiptRequestTestParameters = {[key: string]: unknown};

export interface CreateSampleReceiptRequest {
  contractId: string;
  commissionCode: string;
  commissionDate: string;
  commissionRegisterCode?: string;
  commissionRegisterDate?: string;
  categoryCode: string;
  projectName?: string;
  clientUnit?: string;
  buildingUnit?: string;
  supervisorUnit?: string;
  constructionUnit?: string;
  witnessUnit?: string;
  samplingLocation?: string;
  witness?: string;
  witnessPhone?: string;
  inspector?: string;
  inspectorPhone?: string;
  receivedBy: string;
  sampleSource: string;
  testCategory: string;
  testEnvironment?: string;
  mainEquipment?: string;
  testOperator?: string;
  testStartDate?: string;
  testEndDate?: string;
  originalRecordNo?: string;
  remark?: string;
  judgmentBasis?: string[];
  testingBasis?: string[];
  testParameters?: CreateSampleReceiptRequestTestParameters;
}

export type CreateSampleRequestExt = {[key: string]: string};

export interface CreateSampleRequest {
  receiptId: string;
  sampleCode: string;
  sampleName?: string;
  model?: string;
  specification?: string;
  grade?: string;
  brand?: string;
  manufacturer?: string;
  structuralPart?: string;
  representQuantity?: string;
  sampleQuantity?: string;
  batchNumber?: string;
  supplyUnit?: string;
  arrivalDate?: string;
  samplingDate?: string;
  curingCondition?: string;
  age?: string;
  ext?: CreateSampleRequestExt;
  remark?: string;
}

export interface CreateTechnicalRequirementRequest {
  inspectionObjectCode: string;
  inspectionParameterCode: string;
  judgmentStandardCode: string;
  conditions?: string;
  valueType?: RequirementValueType;
  minValue?: number;
  maxValue?: number;
  targetValue?: string;
  expression?: string;
  unit?: string;
  comparison?: RequirementComparison;
  judgmentMode?: RequirementJudgmentMode;
  verificationStatus?: RequirementVerificationStatus;
  clause?: string;
  sourcePage?: number;
  sourceHash?: string;
  brand?: string;
  model?: string;
  grade?: string;
  spec?: string;
  sieve?: string;
  remark?: string;
  sortOrder?: number;
}

export interface CreateTestRecordRequest {
  sampleId: string;
  parameterCode: string;
  standardCode?: string;
  requirementCode?: string;
  requirement: string;
  result: string;
  verdict?: string;
}

export interface CurrentUser {
  id: string;
  username: string;
  displayName?: string;
  roleCode?: string;
}

export type DashboardStatsReportCountByStatus = {
  draft: number;
  reviewing: number;
  issued: number;
};

export interface DashboardStats {
  contractCount: number;
  receiptCount: number;
  sampleCount: number;
  reportCountByStatus: DashboardStatsReportCountByStatus;
  pendingTaskCount: number;
}

export type ErrorResponseDetails = {[key: string]: unknown};

export interface ErrorResponse {
  code: string;
  message: string;
  details?: ErrorResponseDetails;
}

export type FlowAction = typeof FlowAction[keyof typeof FlowAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FlowAction = {
  submit: 'submit',
  return: 'return',
  withdraw: 'withdraw',
} as const;

export interface FlowActionRequest {
  ids: string[];
  action: FlowAction;
  operator: string;
  reason?: string;
}

export interface FlowActionResult {
  id: string;
  ok: boolean;
  message?: string;
  flowStatus?: FlowStatus;
}

export interface FlowHistoryEntry {
  action: FlowAction;
  from: FlowStatus;
  to: FlowStatus;
  operator: string;
  at: string;
  reason?: string;
}

export type FlowStatus = typeof FlowStatus[keyof typeof FlowStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FlowStatus = {
  receiving: 'receiving',
  task_assignment: 'task_assignment',
  data_entry: 'data_entry',
  review: 'review',
  approval: 'approval',
  issuance: 'issuance',
  archived: 'archived',
  completed: 'completed',
} as const;

export interface InspectionBrand {
  code: string;
  inspectionObjectCode?: string;
  name: string;
  remark?: string;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface InspectionGrade {
  code: string;
  inspectionObjectCode?: string;
  name: string;
  remark?: string;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface InspectionModel {
  code: string;
  inspectionObjectCode?: string;
  name: string;
  remark?: string;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface InspectionSpec {
  code: string;
  inspectionObjectCode?: string;
  name: string;
  remark?: string;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface LoginResponse {
  token: string;
  refreshToken?: string;
  user: CurrentUser;
}

export interface MenuNode {
  id: string;
  label: string;
  path?: string;
  icon?: string;
  children?: MenuNode[];
}

export interface PermissionSet {
  permissions: string[];
}

export type ReceiptResult = typeof ReceiptResult[keyof typeof ReceiptResult];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReceiptResult = {
  pass: 'pass',
  fail: 'fail',
  '': '',
} as const;

export interface RefreshTokenRequest {
  refreshToken: string;
}

export type RequirementComparison = typeof RequirementComparison[keyof typeof RequirementComparison];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequirementComparison = {
  '≥': '≥',
  '≤': '≤',
  '=': '=',
  range: 'range',
  eq: 'eq',
} as const;

export type RequirementJudgmentMode = typeof RequirementJudgmentMode[keyof typeof RequirementJudgmentMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequirementJudgmentMode = {
  automatic: 'automatic',
  manual: 'manual',
} as const;

export type RequirementValueType = typeof RequirementValueType[keyof typeof RequirementValueType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequirementValueType = {
  numeric: 'numeric',
  string: 'string',
  range: 'range',
  formula: 'formula',
  manual: 'manual',
} as const;

export type RequirementVerificationStatus = typeof RequirementVerificationStatus[keyof typeof RequirementVerificationStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequirementVerificationStatus = {
  draft: 'draft',
  reviewed: 'reviewed',
  verified: 'verified',
  rejected: 'rejected',
} as const;

export type SampleExt = {[key: string]: string};

export interface Sample {
  id: string;
  receiptId: string;
  sampleCode: string;
  sampleName?: string;
  model?: string;
  specification?: string;
  grade?: string;
  brand?: string;
  manufacturer?: string;
  structuralPart?: string;
  representQuantity?: string;
  sampleQuantity?: string;
  batchNumber?: string;
  supplyUnit?: string;
  arrivalDate?: string;
  samplingDate?: string;
  curingCondition?: string;
  age?: string;
  ext: SampleExt;
  remark?: string;
  createdAt: string;
  updatedAt: string;
}

export type SampleReceiptTestParameters = {[key: string]: unknown};

export interface SampleReceipt {
  id: string;
  contractId: string;
  commissionCode: string;
  commissionDate: string;
  commissionRegisterCode?: string;
  commissionRegisterDate?: string;
  categoryCode: string;
  projectName?: string;
  clientUnit?: string;
  buildingUnit?: string;
  supervisorUnit?: string;
  constructionUnit?: string;
  witnessUnit?: string;
  samplingLocation?: string;
  witness?: string;
  witnessPhone?: string;
  inspector?: string;
  inspectorPhone?: string;
  receivedBy: string;
  sampleSource: string;
  testCategory: string;
  testEnvironment?: string;
  mainEquipment?: string;
  testOperator?: string;
  testStartDate?: string;
  testEndDate?: string;
  originalRecordNo?: string;
  remark?: string;
  judgmentBasis?: string[];
  testingBasis?: string[];
  testParameters?: SampleReceiptTestParameters;
  flowStatus: FlowStatus;
  flowHistory: FlowHistoryEntry[];
  lastSubmittedBy?: string;
  assigneeId?: string;
  assigneeName?: string;
  plannedTestDate?: string;
  reportCode?: string;
  reportDate?: string;
  conclusion?: string;
  result?: ReceiptResult;
  issuedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SsoCallbackRequest {
  code: string;
  state: string;
}

export interface SsoRedirect {
  authorizeUrl: string;
  state: string;
}

export interface SummaryColumn {
  key: string;
  label: string;
}

export type SummaryDataRowsItem = {[key: string]: string};

export interface SummaryData {
  summaryName: string;
  columns: SummaryColumn[];
  rows: SummaryDataRowsItem[];
}

export interface TechnicalRequirement {
  inspectionObjectCode: string;
  inspectionParameterCode: string;
  judgmentStandardCode: string;
  conditions?: string;
  valueType: RequirementValueType;
  minValue?: number;
  maxValue?: number;
  targetValue?: string;
  expression?: string;
  unit?: string;
  comparison: RequirementComparison;
  judgmentMode: RequirementJudgmentMode;
  verificationStatus: RequirementVerificationStatus;
  clause?: string;
  sourcePage?: number;
  sourceHash?: string;
  brand?: string;
  model?: string;
  grade?: string;
  spec?: string;
  sieve?: string;
  remark?: string;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface TestRecord {
  id: string;
  sampleId: string;
  parameterCode: string;
  standardCode?: string;
  requirementCode?: string;
  requirement: string;
  result: string;
  verdict?: string;
  createdAt: string;
  updatedAt: string;
}

export interface UpdateCatalogEntryRequest {
  inspectionObjectCode?: string;
  name?: string;
  remark?: string;
  sortOrder?: number;
}

export interface UpdateContractRequest {
  contractCode?: string;
  clientUnit?: string;
  projectName?: string;
  projectLocation?: string;
  constructionUnit?: string;
  inspectionSpecialtyCode?: string;
  buildingUnit?: string;
  supervisorUnit?: string;
  inspectionPerson?: string;
  inspectionPhone?: string;
  witnessUnit?: string;
  witness?: string;
  witnessPhone?: string;
  contactPerson?: string;
  contactPhone?: string;
  entrustedDate?: string;
  status?: ContractStatus;
}

export type UpdateSampleReceiptRequestTestParameters = {[key: string]: unknown};

export interface UpdateSampleReceiptRequest {
  contractId?: string;
  commissionCode?: string;
  commissionDate?: string;
  commissionRegisterCode?: string;
  commissionRegisterDate?: string;
  categoryCode?: string;
  projectName?: string;
  clientUnit?: string;
  buildingUnit?: string;
  supervisorUnit?: string;
  constructionUnit?: string;
  witnessUnit?: string;
  samplingLocation?: string;
  witness?: string;
  witnessPhone?: string;
  inspector?: string;
  inspectorPhone?: string;
  receivedBy?: string;
  sampleSource?: string;
  testCategory?: string;
  testEnvironment?: string;
  mainEquipment?: string;
  testOperator?: string;
  testStartDate?: string;
  testEndDate?: string;
  originalRecordNo?: string;
  remark?: string;
  judgmentBasis?: string[];
  testingBasis?: string[];
  testParameters?: UpdateSampleReceiptRequestTestParameters;
}

export type UpdateSampleRequestExt = {[key: string]: string};

export interface UpdateSampleRequest {
  receiptId?: string;
  sampleCode?: string;
  sampleName?: string;
  model?: string;
  specification?: string;
  grade?: string;
  brand?: string;
  manufacturer?: string;
  structuralPart?: string;
  representQuantity?: string;
  sampleQuantity?: string;
  batchNumber?: string;
  supplyUnit?: string;
  arrivalDate?: string;
  samplingDate?: string;
  curingCondition?: string;
  age?: string;
  ext?: UpdateSampleRequestExt;
  remark?: string;
}

export interface UpdateTechnicalRequirementRequest {
  conditions?: string;
  valueType?: RequirementValueType;
  minValue?: number;
  maxValue?: number;
  targetValue?: string;
  expression?: string;
  unit?: string;
  comparison?: RequirementComparison;
  judgmentMode?: RequirementJudgmentMode;
  verificationStatus?: RequirementVerificationStatus;
  clause?: string;
  sourcePage?: number;
  sourceHash?: string;
  brand?: string;
  model?: string;
  grade?: string;
  spec?: string;
  sieve?: string;
  remark?: string;
  sortOrder?: number;
}

export interface UpdateTestRecordRequest {
  sampleId?: string;
  parameterCode?: string;
  standardCode?: string;
  requirementCode?: string;
  requirement?: string;
  result?: string;
  verdict?: string;
}

export type AuthLogoutBody = {
  token: string;
};

export type AuthSsoAuthorizeParams = {
redirect: string;
};

export type CatalogListBrandsParams = {
inspectionObjectCode?: string;
keyword?: string;
};

export type CatalogListGradesParams = {
inspectionObjectCode?: string;
keyword?: string;
};

export type CatalogListModelsParams = {
inspectionObjectCode?: string;
keyword?: string;
};

export type CatalogListSpecsParams = {
inspectionObjectCode?: string;
keyword?: string;
};

export type ContractsListContractsParams = {
page?: number;
pageSize?: number;
keyword?: string;
status?: ContractStatus;
};

export type ContractsListContracts200 = {
  items: Contract[];
  page: number;
  pageSize: number;
  total: number;
};

export type ReceiptsListReceiptsParams = {
page?: number;
pageSize?: number;
keyword?: string;
contractId?: string;
flowStatus?: FlowStatus;
};

export type ReceiptsListReceipts200 = {
  items: SampleReceipt[];
  page: number;
  pageSize: number;
  total: number;
};

export type ReportFlowListFlowQueueParams = {
stage: FlowStatus;
page?: number;
pageSize?: number;
};

export type ReportFlowListFlowQueue200 = {
  items: SampleReceipt[];
  page: number;
  pageSize: number;
  total: number;
};

export type SamplesListSamplesParams = {
page?: number;
pageSize?: number;
receiptId?: string;
keyword?: string;
};

export type SamplesListSamples200 = {
  items: Sample[];
  page: number;
  pageSize: number;
  total: number;
};

export type SummaryGetReportSummaryParams = {
categoryCode?: string;
dateFrom?: string;
dateTo?: string;
};

export type TechnicalRequirementsListTechnicalRequirementsParams = {
inspectionObjectCode?: string;
inspectionParameterCode?: string;
judgmentStandardCode?: string;
verificationStatus?: RequirementVerificationStatus;
};

export type TestRecordsListTestRecordsParams = {
page?: number;
pageSize?: number;
sampleId?: string;
parameterCode?: string;
};

export type TestRecordsListTestRecords200 = {
  items: TestRecord[];
  page: number;
  pageSize: number;
  total: number;
};

export type TestRecordsSetVerdictBody = {
  verdict: string;
};

