/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CatalogListBrands200,
  CatalogListBrandsParams,
  CatalogListGrades200,
  CatalogListGradesParams,
  CatalogListModels200,
  CatalogListModelsParams,
  CatalogListSpecs200,
  CatalogListSpecsParams,
  CreateCatalogEntryRequest,
  ErrorResponse,
  InspectionBrand,
  InspectionGrade,
  InspectionModel,
  InspectionSpec,
  UpdateCatalogEntryRequest
} from '.././model';





export const catalogListBrands = (
    params?: CatalogListBrandsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CatalogListBrands200>> => {
    
    
    return axios.default.get(
      `/api/catalog/brands`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getCatalogListBrandsQueryKey = (params?: CatalogListBrandsParams,) => {
    return [
    `/api/catalog/brands`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCatalogListBrandsQueryOptions = <TData = Awaited<ReturnType<typeof catalogListBrands>>, TError = AxiosError<ErrorResponse>>(params?: CatalogListBrandsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListBrands>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogListBrandsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogListBrands>>> = ({ signal }) => catalogListBrands(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogListBrands>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogListBrandsQueryResult = NonNullable<Awaited<ReturnType<typeof catalogListBrands>>>
export type CatalogListBrandsQueryError = AxiosError<ErrorResponse>


export function useCatalogListBrands<TData = Awaited<ReturnType<typeof catalogListBrands>>, TError = AxiosError<ErrorResponse>>(
 params: undefined |  CatalogListBrandsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListBrands>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogListBrands>>,
          TError,
          Awaited<ReturnType<typeof catalogListBrands>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogListBrands<TData = Awaited<ReturnType<typeof catalogListBrands>>, TError = AxiosError<ErrorResponse>>(
 params?: CatalogListBrandsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListBrands>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogListBrands>>,
          TError,
          Awaited<ReturnType<typeof catalogListBrands>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogListBrands<TData = Awaited<ReturnType<typeof catalogListBrands>>, TError = AxiosError<ErrorResponse>>(
 params?: CatalogListBrandsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListBrands>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogListBrands<TData = Awaited<ReturnType<typeof catalogListBrands>>, TError = AxiosError<ErrorResponse>>(
 params?: CatalogListBrandsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListBrands>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogListBrandsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const catalogCreateBrand = (
    createCatalogEntryRequest: CreateCatalogEntryRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionBrand>> => {
    
    
    return axios.default.post(
      `/api/catalog/brands`,
      createCatalogEntryRequest,options
    );
  }



export const getCatalogCreateBrandMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogCreateBrand>>, TError,{data: CreateCatalogEntryRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof catalogCreateBrand>>, TError,{data: CreateCatalogEntryRequest}, TContext> => {

const mutationKey = ['catalogCreateBrand'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogCreateBrand>>, {data: CreateCatalogEntryRequest}> = (props) => {
          const {data} = props ?? {};

          return  catalogCreateBrand(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CatalogCreateBrandMutationResult = NonNullable<Awaited<ReturnType<typeof catalogCreateBrand>>>
    export type CatalogCreateBrandMutationBody = CreateCatalogEntryRequest
    export type CatalogCreateBrandMutationError = AxiosError<ErrorResponse>

    export const useCatalogCreateBrand = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogCreateBrand>>, TError,{data: CreateCatalogEntryRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogCreateBrand>>,
        TError,
        {data: CreateCatalogEntryRequest},
        TContext
      > => {

      const mutationOptions = getCatalogCreateBrandMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const catalogUpdateBrand = (
    code: string,
    updateCatalogEntryRequest: UpdateCatalogEntryRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionBrand>> => {
    
    
    return axios.default.put(
      `/api/catalog/brands/${code}`,
      updateCatalogEntryRequest,options
    );
  }



export const getCatalogUpdateBrandMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogUpdateBrand>>, TError,{code: string;data: UpdateCatalogEntryRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof catalogUpdateBrand>>, TError,{code: string;data: UpdateCatalogEntryRequest}, TContext> => {

const mutationKey = ['catalogUpdateBrand'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogUpdateBrand>>, {code: string;data: UpdateCatalogEntryRequest}> = (props) => {
          const {code,data} = props ?? {};

          return  catalogUpdateBrand(code,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CatalogUpdateBrandMutationResult = NonNullable<Awaited<ReturnType<typeof catalogUpdateBrand>>>
    export type CatalogUpdateBrandMutationBody = UpdateCatalogEntryRequest
    export type CatalogUpdateBrandMutationError = AxiosError<ErrorResponse>

    export const useCatalogUpdateBrand = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogUpdateBrand>>, TError,{code: string;data: UpdateCatalogEntryRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogUpdateBrand>>,
        TError,
        {code: string;data: UpdateCatalogEntryRequest},
        TContext
      > => {

      const mutationOptions = getCatalogUpdateBrandMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const catalogDeleteBrand = (
    code: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/catalog/brands/${code}`,options
    );
  }



export const getCatalogDeleteBrandMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogDeleteBrand>>, TError,{code: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof catalogDeleteBrand>>, TError,{code: string}, TContext> => {

const mutationKey = ['catalogDeleteBrand'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogDeleteBrand>>, {code: string}> = (props) => {
          const {code} = props ?? {};

          return  catalogDeleteBrand(code,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CatalogDeleteBrandMutationResult = NonNullable<Awaited<ReturnType<typeof catalogDeleteBrand>>>
    
    export type CatalogDeleteBrandMutationError = AxiosError<ErrorResponse>

    export const useCatalogDeleteBrand = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogDeleteBrand>>, TError,{code: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogDeleteBrand>>,
        TError,
        {code: string},
        TContext
      > => {

      const mutationOptions = getCatalogDeleteBrandMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const catalogListGrades = (
    params?: CatalogListGradesParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CatalogListGrades200>> => {
    
    
    return axios.default.get(
      `/api/catalog/grades`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getCatalogListGradesQueryKey = (params?: CatalogListGradesParams,) => {
    return [
    `/api/catalog/grades`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCatalogListGradesQueryOptions = <TData = Awaited<ReturnType<typeof catalogListGrades>>, TError = AxiosError<ErrorResponse>>(params?: CatalogListGradesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListGrades>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogListGradesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogListGrades>>> = ({ signal }) => catalogListGrades(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogListGrades>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogListGradesQueryResult = NonNullable<Awaited<ReturnType<typeof catalogListGrades>>>
export type CatalogListGradesQueryError = AxiosError<ErrorResponse>


export function useCatalogListGrades<TData = Awaited<ReturnType<typeof catalogListGrades>>, TError = AxiosError<ErrorResponse>>(
 params: undefined |  CatalogListGradesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListGrades>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogListGrades>>,
          TError,
          Awaited<ReturnType<typeof catalogListGrades>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogListGrades<TData = Awaited<ReturnType<typeof catalogListGrades>>, TError = AxiosError<ErrorResponse>>(
 params?: CatalogListGradesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListGrades>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogListGrades>>,
          TError,
          Awaited<ReturnType<typeof catalogListGrades>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogListGrades<TData = Awaited<ReturnType<typeof catalogListGrades>>, TError = AxiosError<ErrorResponse>>(
 params?: CatalogListGradesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListGrades>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogListGrades<TData = Awaited<ReturnType<typeof catalogListGrades>>, TError = AxiosError<ErrorResponse>>(
 params?: CatalogListGradesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListGrades>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogListGradesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const catalogCreateGrade = (
    createCatalogEntryRequest: CreateCatalogEntryRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionGrade>> => {
    
    
    return axios.default.post(
      `/api/catalog/grades`,
      createCatalogEntryRequest,options
    );
  }



export const getCatalogCreateGradeMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogCreateGrade>>, TError,{data: CreateCatalogEntryRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof catalogCreateGrade>>, TError,{data: CreateCatalogEntryRequest}, TContext> => {

const mutationKey = ['catalogCreateGrade'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogCreateGrade>>, {data: CreateCatalogEntryRequest}> = (props) => {
          const {data} = props ?? {};

          return  catalogCreateGrade(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CatalogCreateGradeMutationResult = NonNullable<Awaited<ReturnType<typeof catalogCreateGrade>>>
    export type CatalogCreateGradeMutationBody = CreateCatalogEntryRequest
    export type CatalogCreateGradeMutationError = AxiosError<ErrorResponse>

    export const useCatalogCreateGrade = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogCreateGrade>>, TError,{data: CreateCatalogEntryRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogCreateGrade>>,
        TError,
        {data: CreateCatalogEntryRequest},
        TContext
      > => {

      const mutationOptions = getCatalogCreateGradeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const catalogUpdateGrade = (
    code: string,
    updateCatalogEntryRequest: UpdateCatalogEntryRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionGrade>> => {
    
    
    return axios.default.put(
      `/api/catalog/grades/${code}`,
      updateCatalogEntryRequest,options
    );
  }



export const getCatalogUpdateGradeMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogUpdateGrade>>, TError,{code: string;data: UpdateCatalogEntryRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof catalogUpdateGrade>>, TError,{code: string;data: UpdateCatalogEntryRequest}, TContext> => {

const mutationKey = ['catalogUpdateGrade'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogUpdateGrade>>, {code: string;data: UpdateCatalogEntryRequest}> = (props) => {
          const {code,data} = props ?? {};

          return  catalogUpdateGrade(code,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CatalogUpdateGradeMutationResult = NonNullable<Awaited<ReturnType<typeof catalogUpdateGrade>>>
    export type CatalogUpdateGradeMutationBody = UpdateCatalogEntryRequest
    export type CatalogUpdateGradeMutationError = AxiosError<ErrorResponse>

    export const useCatalogUpdateGrade = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogUpdateGrade>>, TError,{code: string;data: UpdateCatalogEntryRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogUpdateGrade>>,
        TError,
        {code: string;data: UpdateCatalogEntryRequest},
        TContext
      > => {

      const mutationOptions = getCatalogUpdateGradeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const catalogDeleteGrade = (
    code: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/catalog/grades/${code}`,options
    );
  }



export const getCatalogDeleteGradeMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogDeleteGrade>>, TError,{code: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof catalogDeleteGrade>>, TError,{code: string}, TContext> => {

const mutationKey = ['catalogDeleteGrade'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogDeleteGrade>>, {code: string}> = (props) => {
          const {code} = props ?? {};

          return  catalogDeleteGrade(code,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CatalogDeleteGradeMutationResult = NonNullable<Awaited<ReturnType<typeof catalogDeleteGrade>>>
    
    export type CatalogDeleteGradeMutationError = AxiosError<ErrorResponse>

    export const useCatalogDeleteGrade = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogDeleteGrade>>, TError,{code: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogDeleteGrade>>,
        TError,
        {code: string},
        TContext
      > => {

      const mutationOptions = getCatalogDeleteGradeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const catalogListModels = (
    params?: CatalogListModelsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CatalogListModels200>> => {
    
    
    return axios.default.get(
      `/api/catalog/models`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getCatalogListModelsQueryKey = (params?: CatalogListModelsParams,) => {
    return [
    `/api/catalog/models`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCatalogListModelsQueryOptions = <TData = Awaited<ReturnType<typeof catalogListModels>>, TError = AxiosError<ErrorResponse>>(params?: CatalogListModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListModels>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogListModelsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogListModels>>> = ({ signal }) => catalogListModels(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogListModels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogListModelsQueryResult = NonNullable<Awaited<ReturnType<typeof catalogListModels>>>
export type CatalogListModelsQueryError = AxiosError<ErrorResponse>


export function useCatalogListModels<TData = Awaited<ReturnType<typeof catalogListModels>>, TError = AxiosError<ErrorResponse>>(
 params: undefined |  CatalogListModelsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListModels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogListModels>>,
          TError,
          Awaited<ReturnType<typeof catalogListModels>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogListModels<TData = Awaited<ReturnType<typeof catalogListModels>>, TError = AxiosError<ErrorResponse>>(
 params?: CatalogListModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListModels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogListModels>>,
          TError,
          Awaited<ReturnType<typeof catalogListModels>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogListModels<TData = Awaited<ReturnType<typeof catalogListModels>>, TError = AxiosError<ErrorResponse>>(
 params?: CatalogListModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListModels>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogListModels<TData = Awaited<ReturnType<typeof catalogListModels>>, TError = AxiosError<ErrorResponse>>(
 params?: CatalogListModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListModels>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogListModelsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const catalogCreateModel = (
    createCatalogEntryRequest: CreateCatalogEntryRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionModel>> => {
    
    
    return axios.default.post(
      `/api/catalog/models`,
      createCatalogEntryRequest,options
    );
  }



export const getCatalogCreateModelMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogCreateModel>>, TError,{data: CreateCatalogEntryRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof catalogCreateModel>>, TError,{data: CreateCatalogEntryRequest}, TContext> => {

const mutationKey = ['catalogCreateModel'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogCreateModel>>, {data: CreateCatalogEntryRequest}> = (props) => {
          const {data} = props ?? {};

          return  catalogCreateModel(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CatalogCreateModelMutationResult = NonNullable<Awaited<ReturnType<typeof catalogCreateModel>>>
    export type CatalogCreateModelMutationBody = CreateCatalogEntryRequest
    export type CatalogCreateModelMutationError = AxiosError<ErrorResponse>

    export const useCatalogCreateModel = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogCreateModel>>, TError,{data: CreateCatalogEntryRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogCreateModel>>,
        TError,
        {data: CreateCatalogEntryRequest},
        TContext
      > => {

      const mutationOptions = getCatalogCreateModelMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const catalogUpdateModel = (
    code: string,
    updateCatalogEntryRequest: UpdateCatalogEntryRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionModel>> => {
    
    
    return axios.default.put(
      `/api/catalog/models/${code}`,
      updateCatalogEntryRequest,options
    );
  }



export const getCatalogUpdateModelMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogUpdateModel>>, TError,{code: string;data: UpdateCatalogEntryRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof catalogUpdateModel>>, TError,{code: string;data: UpdateCatalogEntryRequest}, TContext> => {

const mutationKey = ['catalogUpdateModel'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogUpdateModel>>, {code: string;data: UpdateCatalogEntryRequest}> = (props) => {
          const {code,data} = props ?? {};

          return  catalogUpdateModel(code,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CatalogUpdateModelMutationResult = NonNullable<Awaited<ReturnType<typeof catalogUpdateModel>>>
    export type CatalogUpdateModelMutationBody = UpdateCatalogEntryRequest
    export type CatalogUpdateModelMutationError = AxiosError<ErrorResponse>

    export const useCatalogUpdateModel = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogUpdateModel>>, TError,{code: string;data: UpdateCatalogEntryRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogUpdateModel>>,
        TError,
        {code: string;data: UpdateCatalogEntryRequest},
        TContext
      > => {

      const mutationOptions = getCatalogUpdateModelMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const catalogDeleteModel = (
    code: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/catalog/models/${code}`,options
    );
  }



export const getCatalogDeleteModelMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogDeleteModel>>, TError,{code: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof catalogDeleteModel>>, TError,{code: string}, TContext> => {

const mutationKey = ['catalogDeleteModel'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogDeleteModel>>, {code: string}> = (props) => {
          const {code} = props ?? {};

          return  catalogDeleteModel(code,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CatalogDeleteModelMutationResult = NonNullable<Awaited<ReturnType<typeof catalogDeleteModel>>>
    
    export type CatalogDeleteModelMutationError = AxiosError<ErrorResponse>

    export const useCatalogDeleteModel = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogDeleteModel>>, TError,{code: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogDeleteModel>>,
        TError,
        {code: string},
        TContext
      > => {

      const mutationOptions = getCatalogDeleteModelMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const catalogListSpecs = (
    params?: CatalogListSpecsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CatalogListSpecs200>> => {
    
    
    return axios.default.get(
      `/api/catalog/specs`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getCatalogListSpecsQueryKey = (params?: CatalogListSpecsParams,) => {
    return [
    `/api/catalog/specs`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCatalogListSpecsQueryOptions = <TData = Awaited<ReturnType<typeof catalogListSpecs>>, TError = AxiosError<ErrorResponse>>(params?: CatalogListSpecsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListSpecs>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatalogListSpecsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof catalogListSpecs>>> = ({ signal }) => catalogListSpecs(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catalogListSpecs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatalogListSpecsQueryResult = NonNullable<Awaited<ReturnType<typeof catalogListSpecs>>>
export type CatalogListSpecsQueryError = AxiosError<ErrorResponse>


export function useCatalogListSpecs<TData = Awaited<ReturnType<typeof catalogListSpecs>>, TError = AxiosError<ErrorResponse>>(
 params: undefined |  CatalogListSpecsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListSpecs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogListSpecs>>,
          TError,
          Awaited<ReturnType<typeof catalogListSpecs>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogListSpecs<TData = Awaited<ReturnType<typeof catalogListSpecs>>, TError = AxiosError<ErrorResponse>>(
 params?: CatalogListSpecsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListSpecs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catalogListSpecs>>,
          TError,
          Awaited<ReturnType<typeof catalogListSpecs>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatalogListSpecs<TData = Awaited<ReturnType<typeof catalogListSpecs>>, TError = AxiosError<ErrorResponse>>(
 params?: CatalogListSpecsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListSpecs>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatalogListSpecs<TData = Awaited<ReturnType<typeof catalogListSpecs>>, TError = AxiosError<ErrorResponse>>(
 params?: CatalogListSpecsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catalogListSpecs>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatalogListSpecsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const catalogCreateSpec = (
    createCatalogEntryRequest: CreateCatalogEntryRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionSpec>> => {
    
    
    return axios.default.post(
      `/api/catalog/specs`,
      createCatalogEntryRequest,options
    );
  }



export const getCatalogCreateSpecMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogCreateSpec>>, TError,{data: CreateCatalogEntryRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof catalogCreateSpec>>, TError,{data: CreateCatalogEntryRequest}, TContext> => {

const mutationKey = ['catalogCreateSpec'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogCreateSpec>>, {data: CreateCatalogEntryRequest}> = (props) => {
          const {data} = props ?? {};

          return  catalogCreateSpec(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CatalogCreateSpecMutationResult = NonNullable<Awaited<ReturnType<typeof catalogCreateSpec>>>
    export type CatalogCreateSpecMutationBody = CreateCatalogEntryRequest
    export type CatalogCreateSpecMutationError = AxiosError<ErrorResponse>

    export const useCatalogCreateSpec = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogCreateSpec>>, TError,{data: CreateCatalogEntryRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogCreateSpec>>,
        TError,
        {data: CreateCatalogEntryRequest},
        TContext
      > => {

      const mutationOptions = getCatalogCreateSpecMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const catalogUpdateSpec = (
    code: string,
    updateCatalogEntryRequest: UpdateCatalogEntryRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<InspectionSpec>> => {
    
    
    return axios.default.put(
      `/api/catalog/specs/${code}`,
      updateCatalogEntryRequest,options
    );
  }



export const getCatalogUpdateSpecMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogUpdateSpec>>, TError,{code: string;data: UpdateCatalogEntryRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof catalogUpdateSpec>>, TError,{code: string;data: UpdateCatalogEntryRequest}, TContext> => {

const mutationKey = ['catalogUpdateSpec'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogUpdateSpec>>, {code: string;data: UpdateCatalogEntryRequest}> = (props) => {
          const {code,data} = props ?? {};

          return  catalogUpdateSpec(code,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CatalogUpdateSpecMutationResult = NonNullable<Awaited<ReturnType<typeof catalogUpdateSpec>>>
    export type CatalogUpdateSpecMutationBody = UpdateCatalogEntryRequest
    export type CatalogUpdateSpecMutationError = AxiosError<ErrorResponse>

    export const useCatalogUpdateSpec = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogUpdateSpec>>, TError,{code: string;data: UpdateCatalogEntryRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogUpdateSpec>>,
        TError,
        {code: string;data: UpdateCatalogEntryRequest},
        TContext
      > => {

      const mutationOptions = getCatalogUpdateSpecMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const catalogDeleteSpec = (
    code: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/catalog/specs/${code}`,options
    );
  }



export const getCatalogDeleteSpecMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogDeleteSpec>>, TError,{code: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof catalogDeleteSpec>>, TError,{code: string}, TContext> => {

const mutationKey = ['catalogDeleteSpec'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catalogDeleteSpec>>, {code: string}> = (props) => {
          const {code} = props ?? {};

          return  catalogDeleteSpec(code,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CatalogDeleteSpecMutationResult = NonNullable<Awaited<ReturnType<typeof catalogDeleteSpec>>>
    
    export type CatalogDeleteSpecMutationError = AxiosError<ErrorResponse>

    export const useCatalogDeleteSpec = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catalogDeleteSpec>>, TError,{code: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catalogDeleteSpec>>,
        TError,
        {code: string},
        TContext
      > => {

      const mutationOptions = getCatalogDeleteSpecMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    